import type { VehicleCheckType } from '@/lib/vehicles/types'
import type { CheckTemplate } from './types'

export const CHECK_TEMPLATES: CheckTemplate[] = [
  {
    id: 'tpl-pre-use',
    name: 'Driver pre-use walkaround',
    checkType: 'driver_pre_use',
    version: 'v2.4',
    vehicleCategories: ['minibus', 'coach', 'accessible', 'car'],
    frequency: 'Before each duty',
    validityHours: 12,
    evidenceRequired: ['front_photo', 'dashboard', 'signature'],
    blockingAnswers: ['brakes_unsatisfactory', 'tyre_unsafe', 'emergency_exit_blocked'],
    escalationRules: ['dangerous_defect_auto_vor', 'notify_dispatch_on_fail'],
    approvalRequired: false,
    questionCount: 42,
    active: true,
  },
  {
    id: 'tpl-yard-release',
    name: 'Yard release inspection',
    checkType: 'yard_release',
    version: 'v1.8',
    vehicleCategories: ['minibus', 'coach', 'accessible'],
    frequency: 'Before yard release',
    validityHours: 8,
    evidenceRequired: ['bay_scan', 'fuel_level', 'equipment_photo'],
    blockingAnswers: ['vor_active', 'critical_defect_open'],
    escalationRules: ['block_yard_release', 'notify_yard_supervisor'],
    approvalRequired: true,
    questionCount: 28,
    active: true,
  },
  {
    id: 'tpl-yard-return',
    name: 'Yard return inspection',
    checkType: 'yard_return',
    version: 'v1.6',
    vehicleCategories: ['minibus', 'coach', 'accessible', 'car'],
    frequency: 'On vehicle return',
    validityHours: 0,
    evidenceRequired: ['damage_photos', 'mileage', 'parking_bay'],
    blockingAnswers: ['new_damage_unreported'],
    escalationRules: ['create_return_tasks'],
    approvalRequired: false,
    questionCount: 24,
    active: true,
  },
  {
    id: 'tpl-pmi',
    name: 'Post-maintenance / PMI retest',
    checkType: 'pmi',
    version: 'v3.1',
    vehicleCategories: ['minibus', 'coach', 'accessible'],
    frequency: 'After repair before return to service',
    validityHours: 24,
    evidenceRequired: ['repair_order_ref', 'engineer_signoff', 'road_test_notes'],
    blockingAnswers: ['repair_incomplete', 'retest_failed'],
    escalationRules: ['require_maintenance_signoff', 'block_release_until_retest'],
    approvalRequired: true,
    questionCount: 36,
    active: true,
  },
  {
    id: 'tpl-changeover',
    name: 'Driver changeover',
    checkType: 'driver_changeover',
    version: 'v1.2',
    vehicleCategories: ['minibus', 'coach', 'accessible', 'car'],
    frequency: 'On driver change',
    validityHours: 4,
    evidenceRequired: ['mileage', 'key_handover'],
    blockingAnswers: ['warning_lights_active'],
    escalationRules: ['notify_operations'],
    approvalRequired: false,
    questionCount: 14,
    active: true,
  },
]

export function templateForCheckType(checkType: VehicleCheckType): CheckTemplate | undefined {
  return CHECK_TEMPLATES.find((t) => t.checkType === checkType)
}
