import type {
  ActiveOperation,
  KpiCard,
  NotificationItem,
  OperationalChange,
  OperationalException,
  ReadinessSummary,
  ScheduleBlock,
} from './types'

export const DEPOTS = [
  { id: 'all', name: 'All depots' },
  { id: 'wembley', name: 'Wembley Depot' },
  { id: 'croydon', name: 'Croydon Depot' },
]

export const OVERVIEW_KPIS: Record<string, KpiCard[]> = {
  trips: [
    { id: 'trips-total', label: 'Total trips today', value: 62, href: '/trips' },
    { id: 'trips-active', label: 'Trips in progress', value: 18, tone: 'default', href: '/live-operations' },
    { id: 'trips-completed', label: 'Completed', value: 24, tone: 'success', href: '/trips?status=completed' },
    { id: 'trips-upcoming', label: 'Upcoming', value: 14, href: '/trips?status=upcoming' },
    { id: 'trips-unassigned', label: 'Unassigned', value: 6, sublabel: '3 start within 1 hr', tone: 'warning', href: '/dispatch?filter=unassigned' },
    { id: 'trips-late', label: 'Late trips', value: 4, tone: 'danger', href: '/live-operations?filter=late' },
    { id: 'trips-cancelled', label: 'Cancelled', value: 2, href: '/trips?status=cancelled' },
  ],
  drivers: [
    { id: 'drivers-scheduled', label: 'Scheduled', value: 24, href: '/drivers' },
    { id: 'drivers-on-duty', label: 'On duty', value: 19, href: '/drivers?status=on-duty' },
    { id: 'drivers-available', label: 'Available', value: 14, tone: 'success', href: '/drivers?status=available' },
    { id: 'drivers-absent', label: 'Absent', value: 1, tone: 'danger', href: '/drivers?status=absent' },
    { id: 'drivers-wt-limit', label: 'Approaching duty limit', value: 2, tone: 'warning', href: '/drivers?filter=duty-limit' },
  ],
  vehicles: [
    { id: 'vehicles-required', label: 'Required today', value: 22, href: '/vehicles' },
    { id: 'vehicles-available', label: 'Available', value: 16, tone: 'success', href: '/vehicles?status=available' },
    { id: 'vehicles-in-service', label: 'In service', value: 14, href: '/live-operations' },
    { id: 'vehicles-awaiting-check', label: 'Awaiting checks', value: 3, tone: 'warning', href: '/vehicle-checks?status=pending' },
    { id: 'vehicles-vor', label: 'Marked VOR', value: 2, tone: 'danger', href: '/vehicles?status=vor' },
    { id: 'vehicles-maintenance', label: 'In maintenance', value: 1, href: '/maintenance' },
  ],
  safety: [
    { id: 'safety-critical', label: 'Critical exceptions', value: 1, tone: 'danger', href: '/exceptions?severity=critical' },
    { id: 'safety-defects', label: 'Open defects', value: 5, tone: 'warning', href: '/defects?status=open' },
    { id: 'safety-missed-checks', label: 'Missed vehicle checks', value: 2, tone: 'warning', href: '/vehicle-checks?status=missed' },
    { id: 'safety-incidents', label: 'Open incidents', value: 0, tone: 'success', href: '/incidents?status=open' },
    { id: 'safety-docs', label: 'Expired / expiring docs', value: 3, tone: 'warning', href: '/compliance-rules?filter=expiring' },
  ],
}

export const PRIORITY_EXCEPTIONS: OperationalException[] = [
  {
    id: 'EX-1042',
    severity: 'critical',
    title: 'Vehicle check failed',
    category: 'vehicle',
    relatedRecord: 'AB12 CDE',
    relatedHref: '/vehicles/AB12-CDE',
    depot: 'Wembley',
    raisedAt: '08:04',
    ageMinutes: 12,
    slaMinutesRemaining: 3,
    owner: null,
    status: 'new',
    lastUpdate: '08:04',
    recommendedAction: 'Find replacement vehicle and reassign 5 remaining trips',
  },
  {
    id: 'EX-1041',
    severity: 'high',
    title: 'Driver has not started duty',
    category: 'driver',
    relatedRecord: 'Run AM-104',
    relatedHref: '/runs/AM-104',
    depot: 'Wembley',
    raisedAt: '07:58',
    ageMinutes: 18,
    slaMinutesRemaining: 2,
    owner: 'Sarah',
    status: 'assigned',
    lastUpdate: '08:10',
    recommendedAction: 'Contact driver and prepare backup allocation',
  },
  {
    id: 'EX-1039',
    severity: 'medium',
    title: 'Passenger contact unavailable',
    category: 'customer',
    relatedRecord: 'Trip T-9048',
    relatedHref: '/trips/T-9048',
    depot: 'Croydon',
    raisedAt: '07:42',
    ageMinutes: 34,
    slaMinutesRemaining: null,
    owner: 'James',
    status: 'investigating',
    lastUpdate: '08:01',
  },
]

export const DRIVER_READINESS: ReadinessSummary[] = [
  { label: 'Scheduled', count: 24, href: '/drivers' },
  { label: 'Ready for service', count: 19, tone: 'default', href: '/drivers?status=ready' },
  { label: 'Not signed in', count: 3, tone: 'warning', href: '/drivers?status=not-signed-in' },
  { label: 'Compliance blocked', count: 1, tone: 'danger', href: '/drivers?status=compliance-blocked' },
  { label: 'Absent', count: 1, tone: 'danger', href: '/drivers?status=absent' },
]

export const VEHICLE_READINESS: ReadinessSummary[] = [
  { label: 'Available', count: 16, href: '/vehicles?status=available' },
  { label: 'Allocated', count: 14, href: '/vehicles?status=allocated' },
  { label: 'Awaiting pre-use check', count: 3, tone: 'warning', href: '/vehicle-checks?status=pending' },
  { label: 'Restricted', count: 1, tone: 'warning', href: '/vehicles?status=restricted' },
  { label: 'VOR', count: 2, tone: 'danger', href: '/vehicles?status=vor' },
  { label: 'In maintenance', count: 1, href: '/maintenance' },
]

export const SCHEDULE_BLOCKS: ScheduleBlock[] = [
  { period: '06:00–09:30', label: 'School AM', trips: 38, assigned: 36, health: 'attention' },
  { period: '09:30–14:00', label: 'Day transport', trips: 24, assigned: 24, health: 'healthy' },
  { period: '14:00–17:30', label: 'School PM', trips: 41, assigned: 38, health: 'risk' },
  { period: '17:30–22:00', label: 'Evening work', trips: 12, assigned: 10, health: 'attention' },
]

export const RECENT_CHANGES: OperationalChange[] = [
  { id: '1', time: '08:17', description: 'Vehicle AB12 CDE marked VOR', actor: 'System' },
  { id: '2', time: '08:12', description: 'Driver swapped on Run AM-104', actor: 'Sarah' },
  { id: '3', time: '08:05', description: 'Trip T-9012 cancelled', actor: 'James' },
  { id: '4', time: '07:58', description: 'New defect raised — steering issue', actor: 'Jane Smith' },
  { id: '5', time: '07:45', description: 'Run PM-207 reordered', actor: 'Sarah' },
]

export const ALL_EXCEPTIONS: OperationalException[] = [
  ...PRIORITY_EXCEPTIONS,
  {
    id: 'EX-1038',
    severity: 'high',
    title: 'Wheelchair requirement not matched',
    category: 'journey',
    relatedRecord: 'Trip T-9102',
    relatedHref: '/trips/T-9102',
    depot: 'Wembley',
    raisedAt: '07:30',
    ageMinutes: 46,
    slaMinutesRemaining: -5,
    owner: null,
    status: 'new',
    lastUpdate: '07:30',
    recommendedAction: 'Assign wheelchair-accessible vehicle before 08:45 departure',
  },
  {
    id: 'EX-1035',
    severity: 'medium',
    title: 'GPS signal lost',
    category: 'vehicle',
    relatedRecord: 'CD34 EFG',
    relatedHref: '/vehicles/CD34-EFG',
    depot: 'Croydon',
    raisedAt: '07:15',
    ageMinutes: 61,
    slaMinutesRemaining: null,
    owner: 'James',
    status: 'monitoring',
    lastUpdate: '08:00',
  },
  {
    id: 'EX-1032',
    severity: 'low',
    title: 'Message not acknowledged',
    category: 'driver',
    relatedRecord: 'Driver D-018',
    relatedHref: '/drivers/D-018',
    depot: 'Wembley',
    raisedAt: '06:50',
    ageMinutes: 86,
    slaMinutesRemaining: null,
    owner: 'Dispatch',
    status: 'awaiting_external',
    lastUpdate: '07:20',
  },
]

export const ACTIVE_OPERATIONS: ActiveOperation[] = [
  {
    id: 'run-1',
    type: 'run',
    reference: 'SCH-AM-104',
    driver: 'J. Smith',
    vehicle: 'AB12 CDE',
    progress: '3 of 6',
    currentState: 'En route to pickup',
    delayMinutes: 8,
    gpsFreshnessSeconds: 20,
    operationalState: 'Active',
    passengerOnboard: false,
    wheelchair: false,
    escortRequired: false,
    hasException: true,
  },
  {
    id: 'trip-1',
    type: 'trip',
    reference: 'T-9048',
    driver: 'J. Smith',
    vehicle: 'AB12 CDE',
    currentState: 'En route to pickup',
    eta: '08:42',
    delayMinutes: 6,
    gpsFreshnessSeconds: 16,
    operationalState: 'Active',
    passengerOnboard: false,
    wheelchair: true,
    escortRequired: false,
    hasException: true,
  },
  {
    id: 'vehicle-1',
    type: 'vehicle',
    reference: 'GH56 HIJ',
    driver: 'M. Patel',
    vehicle: 'GH56 HIJ',
    currentState: 'Passenger onboard',
    delayMinutes: 0,
    gpsFreshnessSeconds: 8,
    operationalState: 'In service',
    passengerOnboard: true,
    wheelchair: false,
    escortRequired: true,
    hasException: false,
  },
  {
    id: 'vehicle-2',
    type: 'vehicle',
    reference: 'KL78 MNO',
    driver: 'A. Brown',
    vehicle: 'KL78 MNO',
    currentState: 'Returning to depot',
    delayMinutes: 3,
    gpsFreshnessSeconds: 45,
    operationalState: 'In service',
    passengerOnboard: false,
    wheelchair: false,
    escortRequired: false,
    hasException: false,
  },
  {
    id: 'vehicle-3',
    type: 'vehicle',
    reference: 'CD34 EFG',
    driver: 'R. Wilson',
    vehicle: 'CD34 EFG',
    currentState: 'At pickup',
    delayMinutes: 0,
    gpsFreshnessSeconds: null,
    operationalState: 'GPS stale',
    passengerOnboard: false,
    wheelchair: false,
    escortRequired: false,
    hasException: true,
  },
]

export const NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'N-501',
    category: 'vehicle',
    title: 'Vehicle marked VOR',
    body: 'AB12 CDE was marked VOR following a failed vehicle check. Affected runs: 2. Affected trips: 7.',
    relatedRecord: 'AB12 CDE',
    relatedHref: '/vehicles/AB12-CDE',
    receivedAt: '08:17',
    priority: 'high',
    read: false,
    acknowledged: false,
    actionRequired: true,
    actions: [
      { label: 'Open vehicle', href: '/vehicles/AB12-CDE', variant: 'primary' },
      { label: 'View exception', href: '/exceptions/EX-1042', variant: 'secondary' },
    ],
  },
  {
    id: 'N-500',
    category: 'operational',
    title: 'Four trips predicted late',
    body: 'Four trips on Run AM-104 are predicted to be late due to current delay.',
    relatedRecord: 'Run AM-104',
    relatedHref: '/runs/AM-104',
    receivedAt: '08:14',
    priority: 'high',
    read: false,
    acknowledged: false,
    actionRequired: true,
    groupedCount: 4,
    actions: [
      { label: 'Open run', href: '/runs/AM-104', variant: 'primary' },
      { label: 'Open live operations', href: '/live-operations', variant: 'secondary' },
    ],
  },
  {
    id: 'N-498',
    category: 'safety',
    title: 'Safety alert — acknowledgement required',
    body: 'Wembley Depot south gate closure between 10:00 and 14:00. Use north entrance.',
    receivedAt: '07:55',
    priority: 'urgent',
    read: true,
    acknowledged: false,
    actionRequired: true,
    actions: [{ label: 'Acknowledge', variant: 'primary' }],
  },
  {
    id: 'N-495',
    category: 'assignment',
    title: 'Run published',
    body: 'Run PM-207 has been published to driver A. Brown.',
    relatedRecord: 'PM-207',
    relatedHref: '/runs/PM-207',
    receivedAt: '07:30',
    priority: 'normal',
    read: true,
    acknowledged: true,
    actionRequired: false,
    actions: [{ label: 'Open run', href: '/runs/PM-207' }],
  },
  {
    id: 'N-492',
    category: 'system',
    title: 'Live connection restored',
    body: 'Live vehicle positions are available again. Last outage: 4 minutes.',
    receivedAt: '06:48',
    priority: 'low',
    read: true,
    acknowledged: true,
    actionRequired: false,
  },
]

export const EXCEPTION_VIEWS = [
  { id: 'critical', label: 'Critical now' },
  { id: 'unassigned', label: 'Unassigned' },
  { id: 'mine', label: 'Assigned to me' },
  { id: 'sla', label: 'Approaching SLA' },
  { id: 'escalated', label: 'Escalated' },
  { id: 'resolved', label: 'Resolved today' },
]

export const NOTIFICATION_TABS = [
  { id: 'all', label: 'All' },
  { id: 'unread', label: 'Unread' },
  { id: 'action', label: 'Action required' },
  { id: 'mentions', label: 'Mentions' },
  { id: 'system', label: 'System' },
]
