import type { OperationalException } from '@/lib/types'
import { enrichExceptionSuggestions } from './suggested-actions'

/**
 * Multi-module seed catalog so the Exceptions inbox demonstrates the full taxonomy
 * even when live feeds (defects/incidents) are thin.
 */
export const EXCEPTION_CATALOG: OperationalException[] = [
  {
    id: 'CAT-DRV-LATE',
    severity: 'high',
    title: 'Driver late for duty',
    typeCode: 'driver_late',
    category: 'driver',
    description: 'John Smith has not signed on for Run AM-104 — due 07:45.',
    relatedRecord: 'John Smith',
    relatedHref: '/drivers',
    depot: 'Wembley',
    raisedAt: '07:50',
    ageMinutes: 18,
    slaMinutesRemaining: 7,
    owner: 'Dispatch',
    status: 'assigned',
    lastUpdate: '08:00',
    source: 'Driver App',
    driverName: 'John Smith',
    runRef: 'AM-104',
    recommendedAction: 'Contact driver and prepare backup allocation',
    timeline: [
      { at: '07:30', label: 'Duty published' },
      { at: '07:45', label: 'Sign-on due' },
      { at: '07:50', label: 'Exception raised — driver late' },
      { at: '08:00', label: 'Assigned to Dispatch' },
    ],
    notes: [{ id: 'n1', at: '08:00', author: 'Sarah', body: 'Called — no answer. Trying WhatsApp.' }],
    audit: [{ id: 'a1', at: '07:50', actor: 'System', action: 'Exception raised' }],
  },
  {
    id: 'CAT-DRV-ABSENT',
    severity: 'critical',
    title: 'Driver absent',
    typeCode: 'driver_absent',
    category: 'driver',
    description: 'Rebecca Brown marked absent — Run AM-107 has no driver.',
    relatedRecord: 'Rebecca Brown',
    relatedHref: '/drivers',
    depot: 'Wembley',
    raisedAt: '06:55',
    ageMinutes: 73,
    slaMinutesRemaining: -20,
    owner: null,
    status: 'new',
    lastUpdate: '06:55',
    source: 'HR / Roster',
    driverName: 'Rebecca Brown',
    runRef: 'AM-107',
    escalated: true,
    recommendedAction: 'Assign compliant replacement driver immediately',
  },
  {
    id: 'CAT-DRV-CLOCK',
    severity: 'high',
    title: 'Driver failed to clock in',
    typeCode: 'driver_failed_clock_in',
    category: 'driver',
    description: 'Maria Jones did not clock in before departure window.',
    relatedRecord: 'Maria Jones',
    relatedHref: '/drivers',
    depot: 'Croydon',
    raisedAt: '07:40',
    ageMinutes: 28,
    slaMinutesRemaining: 12,
    owner: null,
    status: 'new',
    lastUpdate: '07:40',
    source: 'Driver App',
    driverName: 'Maria Jones',
    runRef: 'AM-112',
  },
  {
    id: 'CAT-DRV-LICENCE',
    severity: 'critical',
    title: 'Driver licence expires today',
    typeCode: 'driver_licence_expired',
    category: 'compliance',
    description: 'John Smith licence expires today — further assignments must be blocked.',
    relatedRecord: 'John Smith',
    relatedHref: '/drivers',
    depot: 'Wembley',
    raisedAt: '06:00',
    ageMinutes: 128,
    slaMinutesRemaining: 10,
    owner: 'Compliance',
    status: 'investigating',
    lastUpdate: '07:30',
    source: 'Compliance',
    driverName: 'John Smith',
    recommendedAction: 'Block further assignments and notify Compliance Manager',
    timeline: [
      { at: '06:00', label: 'Compliance scan flagged expiry' },
      { at: '06:15', label: 'Driver eligibility blocked' },
      { at: '07:30', label: 'Investigation opened' },
    ],
  },
  {
    id: 'CAT-DRV-CPC',
    severity: 'high',
    title: 'CPC expired',
    typeCode: 'cpc_expired',
    category: 'compliance',
    description: 'Sarah Davis CPC expired — not eligible for PCV work.',
    relatedRecord: 'Sarah Davis',
    relatedHref: '/drivers',
    depot: 'Croydon',
    raisedAt: '05:30',
    ageMinutes: 158,
    slaMinutesRemaining: 5,
    owner: 'Compliance',
    status: 'assigned',
    lastUpdate: '07:00',
    source: 'Compliance',
    driverName: 'Sarah Davis',
  },
  {
    id: 'CAT-DRV-OFFLINE',
    severity: 'medium',
    title: 'Driver app offline',
    typeCode: 'driver_app_offline',
    category: 'driver',
    description: 'Alex Patel app has not synced for 45 minutes while on duty.',
    relatedRecord: 'Alex Patel',
    relatedHref: '/drivers',
    depot: 'Wembley',
    raisedAt: '07:20',
    ageMinutes: 48,
    slaMinutesRemaining: 30,
    owner: 'Dispatch',
    status: 'monitoring',
    lastUpdate: '07:55',
    source: 'Telematics',
    driverName: 'Alex Patel',
    vehicleRegistration: 'LK23 ABC',
  },
  {
    id: 'CAT-DRV-DECLINED',
    severity: 'medium',
    title: 'Driver declined booking',
    typeCode: 'driver_declined_booking',
    category: 'driver',
    description: 'Driver declined BK-21840 — booking needs reallocation.',
    relatedRecord: 'BK-21840',
    relatedHref: '/bookings',
    depot: 'Wembley',
    raisedAt: '08:05',
    ageMinutes: 3,
    slaMinutesRemaining: 20,
    owner: null,
    status: 'new',
    lastUpdate: '08:05',
    source: 'Driver App',
    bookingRef: 'BK-21840',
    driverName: 'Tom Hughes',
  },
  {
    id: 'CAT-DRV-HOURS',
    severity: 'critical',
    title: 'Driver exceeded driving hours',
    typeCode: 'driver_exceeded_hours',
    category: 'compliance',
    description: 'Driving hours limit approached — further work blocked.',
    relatedRecord: 'Priya Shah',
    relatedHref: '/drivers',
    depot: 'Croydon',
    raisedAt: '07:10',
    ageMinutes: 58,
    slaMinutesRemaining: -5,
    owner: 'Compliance',
    status: 'action_in_progress',
    lastUpdate: '07:45',
    source: 'Tachograph',
    driverName: 'Priya Shah',
    escalated: true,
  },
  {
    id: 'CAT-VEH-VOR',
    severity: 'critical',
    title: 'Vehicle VOR',
    typeCode: 'vehicle_vor',
    category: 'vehicle',
    description: 'YX21 ABC marked VOR — safety-critical defect open.',
    relatedRecord: 'YX21 ABC',
    relatedHref: '/vehicles',
    depot: 'Wembley',
    raisedAt: '07:48',
    ageMinutes: 20,
    slaMinutesRemaining: 10,
    owner: 'Fleet',
    status: 'investigating',
    lastUpdate: '08:00',
    source: 'Yard / Defects',
    vehicleRegistration: 'YX21 ABC',
    recommendedAction: 'Find replacement vehicle and reassign remaining trips',
    timeline: [
      { at: '07:40', label: 'Defect reported by driver' },
      { at: '07:48', label: 'Vehicle marked VOR' },
      { at: '08:00', label: 'Fleet investigating replacement' },
    ],
  },
  {
    id: 'CAT-VEH-BREAKDOWN',
    severity: 'critical',
    title: 'Vehicle broke down',
    typeCode: 'vehicle_broke_down',
    category: 'vehicle',
    description: 'EO71 NTJ roadside breakdown — passengers onboard.',
    relatedRecord: 'EO71 NTJ',
    relatedHref: '/vehicles',
    depot: 'Croydon',
    raisedAt: '08:02',
    ageMinutes: 6,
    slaMinutesRemaining: 4,
    owner: 'Dispatch',
    status: 'action_in_progress',
    lastUpdate: '08:06',
    source: 'Driver App',
    vehicleRegistration: 'EO71 NTJ',
    driverName: 'Maria Jones',
    passengerName: 'School group AM-112',
    escalated: true,
  },
  {
    id: 'CAT-VEH-INSPECT',
    severity: 'high',
    title: 'Vehicle failed inspection',
    typeCode: 'vehicle_failed_inspection',
    category: 'vehicle',
    description: 'BV21 YHF failed return inspection — cannot release.',
    relatedRecord: 'BV21 YHF',
    relatedHref: '/vehicles',
    depot: 'Wembley',
    raisedAt: '06:40',
    ageMinutes: 88,
    slaMinutesRemaining: 15,
    owner: 'Yard',
    status: 'assigned',
    lastUpdate: '07:20',
    source: 'Yard',
    vehicleRegistration: 'BV21 YHF',
  },
  {
    id: 'CAT-VEH-DEFECT',
    severity: 'high',
    title: 'Vehicle defect reported',
    typeCode: 'vehicle_defect_reported',
    category: 'vehicle',
    description: 'YX21 ABC defect reported — rear light check incomplete.',
    relatedRecord: 'YX21 ABC',
    relatedHref: '/defects',
    depot: 'Wembley',
    raisedAt: '07:48',
    ageMinutes: 20,
    slaMinutesRemaining: 30,
    owner: 'Fleet',
    status: 'investigating',
    lastUpdate: '08:00',
    source: 'Driver App',
    vehicleRegistration: 'YX21 ABC',
  },
  {
    id: 'CAT-VEH-FUEL',
    severity: 'medium',
    title: 'Fuel below threshold',
    typeCode: 'fuel_below_threshold',
    category: 'vehicle',
    description: 'LK23 ABC fuel at 12% — below operational threshold.',
    relatedRecord: 'LK23 ABC',
    relatedHref: '/vehicles',
    depot: 'Wembley',
    raisedAt: '07:55',
    ageMinutes: 13,
    slaMinutesRemaining: 40,
    owner: null,
    status: 'new',
    lastUpdate: '07:55',
    source: 'Telematics',
    vehicleRegistration: 'LK23 ABC',
  },
  {
    id: 'CAT-VEH-EV',
    severity: 'medium',
    title: 'EV battery low',
    typeCode: 'ev_battery_low',
    category: 'vehicle',
    description: 'EV battery at 18% — charge required before next run.',
    relatedRecord: 'EV68 KLM',
    relatedHref: '/vehicles',
    depot: 'Croydon',
    raisedAt: '07:00',
    ageMinutes: 68,
    slaMinutesRemaining: 25,
    owner: 'Yard',
    status: 'assigned',
    lastUpdate: '07:30',
    source: 'Telematics',
    vehicleRegistration: 'EV68 KLM',
  },
  {
    id: 'CAT-VEH-MOT',
    severity: 'critical',
    title: 'MOT expired',
    typeCode: 'mot_expired',
    category: 'compliance',
    description: 'YG68 AKF MOT expired — vehicle must not enter service.',
    relatedRecord: 'YG68 AKF',
    relatedHref: '/vehicles',
    depot: 'Wembley',
    raisedAt: '05:00',
    ageMinutes: 188,
    slaMinutesRemaining: -60,
    owner: 'Compliance',
    status: 'new',
    lastUpdate: '05:00',
    source: 'Compliance',
    vehicleRegistration: 'YG68 AKF',
    escalated: true,
  },
  {
    id: 'CAT-JNY-NOT-COLLECTED',
    severity: 'critical',
    title: 'Passenger not collected',
    typeCode: 'passenger_not_collected',
    category: 'journey',
    description: 'Mary Jones not collected at planned pickup — passenger waiting.',
    relatedRecord: 'BK-21831',
    relatedHref: '/bookings',
    depot: 'Wembley',
    raisedAt: '08:14',
    ageMinutes: 5,
    slaMinutesRemaining: 10,
    owner: 'Operations',
    status: 'new',
    lastUpdate: '08:14',
    source: 'Driver App',
    driverName: 'John Smith',
    vehicleRegistration: 'YX21 ABC',
    passengerName: 'Mary Jones',
    bookingRef: 'BK-21831',
    runRef: 'AM-104',
    timeline: [
      { at: '08:00', label: 'Driver accepted' },
      { at: '08:07', label: 'Arrived at pickup' },
      { at: '08:10', label: 'Passenger not found' },
      { at: '08:12', label: 'Dispatch alerted' },
      { at: '08:14', label: 'Exception raised' },
    ],
    attachments: [{ id: 'att1', name: 'pickup-photo.jpg', kind: 'image' }],
    audit: [
      { id: 'a1', at: '08:14', actor: 'System', action: 'Exception raised from Driver App' },
    ],
  },
  {
    id: 'CAT-JNY-DELAYED',
    severity: 'high',
    title: 'Vehicle delayed',
    typeCode: 'vehicle_delayed',
    category: 'journey',
    description: 'Run AM-104 delayed 12 minutes — at risk of late school arrival.',
    relatedRecord: 'AM-104',
    relatedHref: '/live-operations?duty=AM-104',
    depot: 'Wembley',
    raisedAt: '07:56',
    ageMinutes: 12,
    slaMinutesRemaining: 15,
    owner: 'Operations',
    status: 'investigating',
    lastUpdate: '08:05',
    source: 'Live Operations',
    runRef: 'AM-104',
    vehicleRegistration: 'LK23 ABC',
    driverName: 'John Smith',
  },
  {
    id: 'CAT-JNY-NOSHOW',
    severity: 'medium',
    title: 'Passenger no-show',
    typeCode: 'passenger_no_show',
    category: 'journey',
    description: 'Passenger no-show recorded after wait window.',
    relatedRecord: 'BK-21790',
    relatedHref: '/bookings',
    depot: 'Croydon',
    raisedAt: '07:35',
    ageMinutes: 33,
    slaMinutesRemaining: null,
    owner: 'Operations',
    status: 'awaiting_external',
    lastUpdate: '07:50',
    source: 'Driver App',
    passengerName: 'James Cole',
    bookingRef: 'BK-21790',
  },
  {
    id: 'CAT-JNY-WRONG-VEH',
    severity: 'high',
    title: 'Wrong vehicle assigned',
    typeCode: 'wrong_vehicle_assigned',
    category: 'dispatch',
    description: 'Wheelchair booking assigned to non-accessible vehicle.',
    relatedRecord: 'BK-21812',
    relatedHref: '/bookings',
    depot: 'Wembley',
    raisedAt: '07:25',
    ageMinutes: 43,
    slaMinutesRemaining: 8,
    owner: 'Dispatch',
    status: 'assigned',
    lastUpdate: '07:40',
    source: 'Dispatch',
    bookingRef: 'BK-21812',
    vehicleRegistration: 'AB12 CDE',
  },
  {
    id: 'CAT-JNY-DEVIATION',
    severity: 'medium',
    title: 'Route deviation',
    typeCode: 'route_deviation',
    category: 'journey',
    description: 'Vehicle left planned corridor for more than 3 minutes.',
    relatedRecord: 'AM-112',
    relatedHref: '/live-operations',
    depot: 'Croydon',
    raisedAt: '08:01',
    ageMinutes: 7,
    slaMinutesRemaining: 25,
    owner: null,
    status: 'new',
    lastUpdate: '08:01',
    source: 'Telematics',
    runRef: 'AM-112',
  },
  {
    id: 'CAT-JNY-CANCEL',
    severity: 'low',
    title: 'Trip cancelled',
    typeCode: 'trip_cancelled',
    category: 'journey',
    description: 'Customer cancelled BK-21800 — notify school and clear run slot.',
    relatedRecord: 'BK-21800',
    relatedHref: '/bookings',
    depot: 'Wembley',
    raisedAt: '06:20',
    ageMinutes: 108,
    slaMinutesRemaining: null,
    owner: 'Customer Services',
    status: 'resolved',
    lastUpdate: '07:10',
    source: 'Customer portal',
    bookingRef: 'BK-21800',
  },
  {
    id: 'CAT-CUS-COMPLAINT',
    severity: 'medium',
    title: 'Complaint submitted',
    typeCode: 'complaint_submitted',
    category: 'customer',
    description: 'Parent complaint — late arrival yesterday PM.',
    relatedRecord: 'CMP-441',
    relatedHref: '/incidents',
    depot: 'Wembley',
    raisedAt: '07:00',
    ageMinutes: 68,
    slaMinutesRemaining: 120,
    owner: 'Customer Services',
    status: 'assigned',
    lastUpdate: '07:20',
    source: 'Customer portal',
    passengerName: 'Emma Wright',
  },
  {
    id: 'CAT-CUS-PRIORITY',
    severity: 'high',
    title: 'High priority passenger',
    typeCode: 'high_priority_passenger',
    category: 'customer',
    description: 'Safeguarding-flagged passenger — escort confirmation outstanding.',
    relatedRecord: 'BK-21855',
    relatedHref: '/bookings',
    depot: 'Croydon',
    raisedAt: '07:15',
    ageMinutes: 53,
    slaMinutesRemaining: 10,
    owner: 'Operations',
    status: 'investigating',
    lastUpdate: '07:50',
    source: 'Bookings',
    passengerName: 'Protected passenger',
    bookingRef: 'BK-21855',
  },
  {
    id: 'CAT-CUS-WHEELCHAIR',
    severity: 'high',
    title: 'Wheelchair booking issue',
    typeCode: 'wheelchair_booking_issue',
    category: 'customer',
    description: 'Wheelchair requirement not matched on allocated vehicle.',
    relatedRecord: 'Trip T-9102',
    relatedHref: '/trips',
    depot: 'Wembley',
    raisedAt: '07:30',
    ageMinutes: 46,
    slaMinutesRemaining: -5,
    owner: null,
    status: 'new',
    lastUpdate: '07:30',
    source: 'Dispatch',
    bookingRef: 'T-9102',
  },
  {
    id: 'CAT-CUS-ESCORT',
    severity: 'critical',
    title: 'Escort missing',
    typeCode: 'escort_missing',
    category: 'customer',
    description: 'Required escort not present at pickup — boarding blocked.',
    relatedRecord: 'BK-21860',
    relatedHref: '/bookings',
    depot: 'Wembley',
    raisedAt: '08:08',
    ageMinutes: 0,
    slaMinutesRemaining: 5,
    owner: 'Operations',
    status: 'new',
    lastUpdate: '08:08',
    source: 'Driver App',
    passengerName: 'Noah Ali',
    bookingRef: 'BK-21860',
    escalated: true,
  },
  {
    id: 'CAT-DSP-NO-DRIVER',
    severity: 'critical',
    title: 'Run has no driver',
    typeCode: 'run_no_driver',
    category: 'dispatch',
    description: 'PM-205 has no driver assigned — departure in 40 minutes.',
    relatedRecord: 'PM-205',
    relatedHref: '/dispatch',
    depot: 'Wembley',
    raisedAt: '07:45',
    ageMinutes: 23,
    slaMinutesRemaining: 15,
    owner: null,
    status: 'new',
    lastUpdate: '07:45',
    source: 'Dispatch',
    runRef: 'PM-205',
  },
  {
    id: 'CAT-DSP-NO-VEHICLE',
    severity: 'critical',
    title: 'Run has no vehicle',
    typeCode: 'run_no_vehicle',
    category: 'dispatch',
    description: 'AM-118 has no vehicle — 6 passengers affected.',
    relatedRecord: 'AM-118',
    relatedHref: '/dispatch',
    depot: 'Croydon',
    raisedAt: '07:00',
    ageMinutes: 68,
    slaMinutesRemaining: -10,
    owner: 'Dispatch',
    status: 'assigned',
    lastUpdate: '07:40',
    source: 'Dispatch',
    runRef: 'AM-118',
    escalated: true,
  },
  {
    id: 'CAT-DSP-CAPACITY',
    severity: 'high',
    title: 'Capacity exceeded',
    typeCode: 'capacity_exceeded',
    category: 'dispatch',
    description: 'Run AM-104 capacity exceeded by 2 seats.',
    relatedRecord: 'AM-104',
    relatedHref: '/dispatch',
    depot: 'Wembley',
    raisedAt: '07:20',
    ageMinutes: 48,
    slaMinutesRemaining: 20,
    owner: 'Dispatch',
    status: 'investigating',
    lastUpdate: '07:50',
    source: 'Dispatch',
    runRef: 'AM-104',
  },
  {
    id: 'CAT-DSP-DOUBLE',
    severity: 'high',
    title: 'Double booking',
    typeCode: 'double_booking',
    category: 'dispatch',
    description: 'Vehicle LK23 ABC double-booked across two overlapping runs.',
    relatedRecord: 'LK23 ABC',
    relatedHref: '/dispatch',
    depot: 'Wembley',
    raisedAt: '06:50',
    ageMinutes: 78,
    slaMinutesRemaining: 5,
    owner: 'Dispatch',
    status: 'action_in_progress',
    lastUpdate: '07:55',
    source: 'Dispatch',
    vehicleRegistration: 'LK23 ABC',
  },
  {
    id: 'CAT-CMP-CHECKS',
    severity: 'high',
    title: 'Daily checks missing',
    typeCode: 'daily_checks_missing',
    category: 'compliance',
    description: 'Pre-use checks not completed for three vehicles due out.',
    relatedRecord: 'Vehicle checks',
    relatedHref: '/vehicle-checks',
    depot: 'Wembley',
    raisedAt: '06:30',
    ageMinutes: 98,
    slaMinutesRemaining: 20,
    owner: 'Yard',
    status: 'assigned',
    lastUpdate: '07:10',
    source: 'Compliance',
  },
  {
    id: 'CAT-CMP-INCIDENT',
    severity: 'critical',
    title: 'Incident awaiting review',
    typeCode: 'incident_awaiting_review',
    category: 'compliance',
    description: 'Safeguarding incident open — evidence pack incomplete.',
    relatedRecord: 'INC-902',
    relatedHref: '/incidents',
    depot: 'Croydon',
    raisedAt: '05:45',
    ageMinutes: 143,
    slaMinutesRemaining: -30,
    owner: 'Compliance',
    status: 'awaiting_external',
    lastUpdate: '07:00',
    source: 'Incidents',
    escalated: true,
  },
  {
    id: 'CAT-YARD-NOT-RETURNED',
    severity: 'high',
    title: 'Vehicle not returned',
    typeCode: 'vehicle_not_returned',
    category: 'yard',
    description: 'CD34 EFG expected back 18:00 yesterday — still off site.',
    relatedRecord: 'CD34 EFG',
    relatedHref: '/yard',
    depot: 'Wembley',
    raisedAt: '06:00',
    ageMinutes: 128,
    slaMinutesRemaining: 30,
    owner: 'Yard',
    status: 'investigating',
    lastUpdate: '07:30',
    source: 'Yard',
    vehicleRegistration: 'CD34 EFG',
  },
  {
    id: 'CAT-YARD-KEYS',
    severity: 'medium',
    title: 'Keys missing',
    typeCode: 'keys_missing',
    category: 'yard',
    description: 'Key set for AB12 CDE not in cabinet — bay B12.',
    relatedRecord: 'AB12 CDE',
    relatedHref: '/yard',
    depot: 'Wembley',
    raisedAt: '07:10',
    ageMinutes: 58,
    slaMinutesRemaining: 45,
    owner: 'Yard',
    status: 'assigned',
    lastUpdate: '07:40',
    source: 'Yard',
    vehicleRegistration: 'AB12 CDE',
  },
  {
    id: 'CAT-YARD-EQUIP',
    severity: 'medium',
    title: 'Equipment missing',
    typeCode: 'equipment_missing',
    category: 'yard',
    description: 'Wheelchair ramp missing from EO71 NTJ before departure.',
    relatedRecord: 'EO71 NTJ',
    relatedHref: '/yard',
    depot: 'Croydon',
    raisedAt: '07:50',
    ageMinutes: 18,
    slaMinutesRemaining: 20,
    owner: null,
    status: 'new',
    lastUpdate: '07:50',
    source: 'Yard',
    vehicleRegistration: 'EO71 NTJ',
  },
  {
    id: 'CAT-YARD-CLEAN',
    severity: 'low',
    title: 'Cleaning overdue',
    typeCode: 'cleaning_overdue',
    category: 'yard',
    description: 'Interior clean overdue for two school vehicles.',
    relatedRecord: 'Yard cleaning',
    relatedHref: '/yard',
    depot: 'Wembley',
    raisedAt: '06:15',
    ageMinutes: 113,
    slaMinutesRemaining: null,
    owner: 'Yard',
    status: 'monitoring',
    lastUpdate: '07:00',
    source: 'Yard',
  },
].map((ex) => enrichExceptionSuggestions(ex as OperationalException))
