/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as PublicUpdateRequiredRouteImport } from './routes/_public.update-required'
import { Route as PublicSplashRouteImport } from './routes/_public.splash'
import { Route as PublicSignInRouteImport } from './routes/_public.sign-in'
import { Route as PublicMfaRouteImport } from './routes/_public.mfa'
import { Route as PublicInitialSyncRouteImport } from './routes/_public.initial-sync'
import { Route as PublicDepotSelectRouteImport } from './routes/_public.depot-select'
import { Route as PublicCompanySelectRouteImport } from './routes/_public.company-select'
import { Route as PublicBiometricUnlockRouteImport } from './routes/_public.biometric-unlock'
import { Route as PublicAccountRestrictedRouteImport } from './routes/_public.account-restricted'
import { Route as AppYardRouteImport } from './routes/_app.yard'
import { Route as AppVorRouteImport } from './routes/_app.vor'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppShiftRouteImport } from './routes/_app.shift'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppMovementsRouteImport } from './routes/_app.movements'
import { Route as AppMoreRouteImport } from './routes/_app.more'
import { Route as AppInspectionsRouteImport } from './routes/_app.inspections'
import { Route as AppDepartureLineRouteImport } from './routes/_app.departure-line'
import { Route as AppDefectsRouteImport } from './routes/_app.defects'
import { Route as AppChecksRouteImport } from './routes/_app.checks'
import { Route as AppArrivalsRouteImport } from './routes/_app.arrivals'
import { Route as AppYardIndexRouteImport } from './routes/_app.yard.index'
import { Route as AppVorIndexRouteImport } from './routes/_app.vor.index'
import { Route as AppTasksIndexRouteImport } from './routes/_app.tasks.index'
import { Route as AppMoreIndexRouteImport } from './routes/_app.more.index'
import { Route as AppInspectionsIndexRouteImport } from './routes/_app.inspections.index'
import { Route as AppDefectsIndexRouteImport } from './routes/_app.defects.index'
import { Route as AppChecksIndexRouteImport } from './routes/_app.checks.index'
import { Route as PublicWelcomeStepRouteImport } from './routes/_public.welcome.$step'
import { Route as AppYardMapRouteImport } from './routes/_app.yard.map'
import { Route as AppYardVehicleIdRouteImport } from './routes/_app.yard.$vehicleId'
import { Route as AppVorCaseIdRouteImport } from './routes/_app.vor.$caseId'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app.tasks.$taskId'
import { Route as AppSimulateDriverReportRouteImport } from './routes/_app.simulate.driver-report'
import { Route as AppMoreVehicleChecksRouteImport } from './routes/_app.more.vehicle-checks'
import { Route as AppMoreSyncRouteImport } from './routes/_app.more.sync'
import { Route as AppMoreSettingsRouteImport } from './routes/_app.more.settings'
import { Route as AppMoreMessagesRouteImport } from './routes/_app.more.messages'
import { Route as AppMoreBodyworkRouteImport } from './routes/_app.more.bodywork'
import { Route as AppMoreAccountRouteImport } from './routes/_app.more.account'
import { Route as AppMoreAboutRouteImport } from './routes/_app.more.about'
import { Route as AppInspectionsRepairVerificationRouteImport } from './routes/_app.inspections.repair-verification'
import { Route as AppInspectionsDamageReviewRouteImport } from './routes/_app.inspections.damage-review'
import { Route as AppInspectionsAnalyticsRouteImport } from './routes/_app.inspections.analytics'
import { Route as AppDefectsDefectIdRouteImport } from './routes/_app.defects.$defectId'
import { Route as AppChecksCheckIdRouteImport } from './routes/_app.checks.$checkId'
import { Route as AppYardVehicleIdIndexRouteImport } from './routes/_app.yard.$vehicleId.index'
import { Route as ApiV1YardMutationsRouteImport } from './routes/api/v1/yard/mutations'
import { Route as ApiV1YardHealthRouteImport } from './routes/api/v1/yard/health'
import { Route as ApiV1YardBootstrapRouteImport } from './routes/api/v1/yard/bootstrap'
import { Route as AppYardVehicleIdEquipmentRouteImport } from './routes/_app.yard.$vehicleId.equipment'
import { Route as AppYardVehicleIdConditionRouteImport } from './routes/_app.yard.$vehicleId.condition'
import { Route as AppYardVehicleIdCheckRouteImport } from './routes/_app.yard.$vehicleId.check'
import { Route as AppYardVehicleIdConditionInspectRouteImport } from './routes/_app.yard.$vehicleId.condition.inspect'
import { Route as AppYardVehicleIdConditionCompareRouteImport } from './routes/_app.yard.$vehicleId.condition.compare'
import { Route as AppYardVehicleIdAdblueRefillRouteImport } from './routes/_app.yard.$vehicleId.adblue.refill'
import { Route as AppYardVehicleIdConditionDamageDamageIdRouteImport } from './routes/_app.yard.$vehicleId.condition.damage.$damageId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PublicUpdateRequiredRoute = PublicUpdateRequiredRouteImport.update({
  id: '/update-required',
  path: '/update-required',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSplashRoute = PublicSplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMfaRoute = PublicMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => PublicRoute,
} as any)
const PublicInitialSyncRoute = PublicInitialSyncRouteImport.update({
  id: '/initial-sync',
  path: '/initial-sync',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDepotSelectRoute = PublicDepotSelectRouteImport.update({
  id: '/depot-select',
  path: '/depot-select',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCompanySelectRoute = PublicCompanySelectRouteImport.update({
  id: '/company-select',
  path: '/company-select',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBiometricUnlockRoute = PublicBiometricUnlockRouteImport.update({
  id: '/biometric-unlock',
  path: '/biometric-unlock',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAccountRestrictedRoute = PublicAccountRestrictedRouteImport.update({
  id: '/account-restricted',
  path: '/account-restricted',
  getParentRoute: () => PublicRoute,
} as any)
const AppYardRoute = AppYardRouteImport.update({
  id: '/yard',
  path: '/yard',
  getParentRoute: () => AppRoute,
} as any)
const AppVorRoute = AppVorRouteImport.update({
  id: '/vor',
  path: '/vor',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftRoute = AppShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartureLineRoute = AppDepartureLineRouteImport.update({
  id: '/departure-line',
  path: '/departure-line',
  getParentRoute: () => AppRoute,
} as any)
const AppDefectsRoute = AppDefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => AppRoute,
} as any)
const AppChecksRoute = AppChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => AppRoute,
} as any)
const AppArrivalsRoute = AppArrivalsRouteImport.update({
  id: '/arrivals',
  path: '/arrivals',
  getParentRoute: () => AppRoute,
} as any)
const AppYardIndexRoute = AppYardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppYardRoute,
} as any)
const AppVorIndexRoute = AppVorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVorRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppMoreIndexRoute = AppMoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppInspectionsIndexRoute = AppInspectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInspectionsRoute,
} as any)
const AppDefectsIndexRoute = AppDefectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDefectsRoute,
} as any)
const AppChecksIndexRoute = AppChecksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChecksRoute,
} as any)
const PublicWelcomeStepRoute = PublicWelcomeStepRouteImport.update({
  id: '/welcome/$step',
  path: '/welcome/$step',
  getParentRoute: () => PublicRoute,
} as any)
const AppYardMapRoute = AppYardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppYardRoute,
} as any)
const AppYardVehicleIdRoute = AppYardVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => AppYardRoute,
} as any)
const AppVorCaseIdRoute = AppVorCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AppVorRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppSimulateDriverReportRoute = AppSimulateDriverReportRouteImport.update({
  id: '/simulate/driver-report',
  path: '/simulate/driver-report',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreVehicleChecksRoute = AppMoreVehicleChecksRouteImport.update({
  id: '/vehicle-checks',
  path: '/vehicle-checks',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreSyncRoute = AppMoreSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreSettingsRoute = AppMoreSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreMessagesRoute = AppMoreMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreBodyworkRoute = AppMoreBodyworkRouteImport.update({
  id: '/bodywork',
  path: '/bodywork',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreAccountRoute = AppMoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreAboutRoute = AppMoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppInspectionsRepairVerificationRoute =
  AppInspectionsRepairVerificationRouteImport.update({
    id: '/repair-verification',
    path: '/repair-verification',
    getParentRoute: () => AppInspectionsRoute,
  } as any)
const AppInspectionsDamageReviewRoute =
  AppInspectionsDamageReviewRouteImport.update({
    id: '/damage-review',
    path: '/damage-review',
    getParentRoute: () => AppInspectionsRoute,
  } as any)
const AppInspectionsAnalyticsRoute = AppInspectionsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppInspectionsRoute,
} as any)
const AppDefectsDefectIdRoute = AppDefectsDefectIdRouteImport.update({
  id: '/$defectId',
  path: '/$defectId',
  getParentRoute: () => AppDefectsRoute,
} as any)
const AppChecksCheckIdRoute = AppChecksCheckIdRouteImport.update({
  id: '/$checkId',
  path: '/$checkId',
  getParentRoute: () => AppChecksRoute,
} as any)
const AppYardVehicleIdIndexRoute = AppYardVehicleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppYardVehicleIdRoute,
} as any)
const ApiV1YardMutationsRoute = ApiV1YardMutationsRouteImport.update({
  id: '/api/v1/yard/mutations',
  path: '/api/v1/yard/mutations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1YardHealthRoute = ApiV1YardHealthRouteImport.update({
  id: '/api/v1/yard/health',
  path: '/api/v1/yard/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1YardBootstrapRoute = ApiV1YardBootstrapRouteImport.update({
  id: '/api/v1/yard/bootstrap',
  path: '/api/v1/yard/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AppYardVehicleIdEquipmentRoute =
  AppYardVehicleIdEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AppYardVehicleIdRoute,
  } as any)
const AppYardVehicleIdConditionRoute =
  AppYardVehicleIdConditionRouteImport.update({
    id: '/condition',
    path: '/condition',
    getParentRoute: () => AppYardVehicleIdRoute,
  } as any)
const AppYardVehicleIdCheckRoute = AppYardVehicleIdCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => AppYardVehicleIdRoute,
} as any)
const AppYardVehicleIdConditionInspectRoute =
  AppYardVehicleIdConditionInspectRouteImport.update({
    id: '/inspect',
    path: '/inspect',
    getParentRoute: () => AppYardVehicleIdConditionRoute,
  } as any)
const AppYardVehicleIdConditionCompareRoute =
  AppYardVehicleIdConditionCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AppYardVehicleIdConditionRoute,
  } as any)
const AppYardVehicleIdAdblueRefillRoute =
  AppYardVehicleIdAdblueRefillRouteImport.update({
    id: '/adblue/refill',
    path: '/adblue/refill',
    getParentRoute: () => AppYardVehicleIdRoute,
  } as any)
const AppYardVehicleIdConditionDamageDamageIdRoute =
  AppYardVehicleIdConditionDamageDamageIdRouteImport.update({
    id: '/damage/$damageId',
    path: '/damage/$damageId',
    getParentRoute: () => AppYardVehicleIdConditionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/arrivals': typeof AppArrivalsRoute
  '/checks': typeof AppChecksRouteWithChildren
  '/defects': typeof AppDefectsRouteWithChildren
  '/departure-line': typeof AppDepartureLineRoute
  '/inspections': typeof AppInspectionsRouteWithChildren
  '/more': typeof AppMoreRouteWithChildren
  '/movements': typeof AppMovementsRoute
  '/scan': typeof AppScanRoute
  '/shift': typeof AppShiftRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/vor': typeof AppVorRouteWithChildren
  '/yard': typeof AppYardRouteWithChildren
  '/account-restricted': typeof PublicAccountRestrictedRoute
  '/biometric-unlock': typeof PublicBiometricUnlockRoute
  '/company-select': typeof PublicCompanySelectRoute
  '/depot-select': typeof PublicDepotSelectRoute
  '/initial-sync': typeof PublicInitialSyncRoute
  '/mfa': typeof PublicMfaRoute
  '/sign-in': typeof PublicSignInRoute
  '/splash': typeof PublicSplashRoute
  '/update-required': typeof PublicUpdateRequiredRoute
  '/checks/$checkId': typeof AppChecksCheckIdRoute
  '/defects/$defectId': typeof AppDefectsDefectIdRoute
  '/inspections/analytics': typeof AppInspectionsAnalyticsRoute
  '/inspections/damage-review': typeof AppInspectionsDamageReviewRoute
  '/inspections/repair-verification': typeof AppInspectionsRepairVerificationRoute
  '/more/about': typeof AppMoreAboutRoute
  '/more/account': typeof AppMoreAccountRoute
  '/more/bodywork': typeof AppMoreBodyworkRoute
  '/more/messages': typeof AppMoreMessagesRoute
  '/more/settings': typeof AppMoreSettingsRoute
  '/more/sync': typeof AppMoreSyncRoute
  '/more/vehicle-checks': typeof AppMoreVehicleChecksRoute
  '/simulate/driver-report': typeof AppSimulateDriverReportRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/vor/$caseId': typeof AppVorCaseIdRoute
  '/yard/$vehicleId': typeof AppYardVehicleIdRouteWithChildren
  '/yard/map': typeof AppYardMapRoute
  '/welcome/$step': typeof PublicWelcomeStepRoute
  '/checks/': typeof AppChecksIndexRoute
  '/defects/': typeof AppDefectsIndexRoute
  '/inspections/': typeof AppInspectionsIndexRoute
  '/more/': typeof AppMoreIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/vor/': typeof AppVorIndexRoute
  '/yard/': typeof AppYardIndexRoute
  '/yard/$vehicleId/check': typeof AppYardVehicleIdCheckRoute
  '/yard/$vehicleId/condition': typeof AppYardVehicleIdConditionRouteWithChildren
  '/yard/$vehicleId/equipment': typeof AppYardVehicleIdEquipmentRoute
  '/api/v1/yard/bootstrap': typeof ApiV1YardBootstrapRoute
  '/api/v1/yard/health': typeof ApiV1YardHealthRoute
  '/api/v1/yard/mutations': typeof ApiV1YardMutationsRoute
  '/yard/$vehicleId/': typeof AppYardVehicleIdIndexRoute
  '/yard/$vehicleId/adblue/refill': typeof AppYardVehicleIdAdblueRefillRoute
  '/yard/$vehicleId/condition/compare': typeof AppYardVehicleIdConditionCompareRoute
  '/yard/$vehicleId/condition/inspect': typeof AppYardVehicleIdConditionInspectRoute
  '/yard/$vehicleId/condition/damage/$damageId': typeof AppYardVehicleIdConditionDamageDamageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/arrivals': typeof AppArrivalsRoute
  '/departure-line': typeof AppDepartureLineRoute
  '/movements': typeof AppMovementsRoute
  '/scan': typeof AppScanRoute
  '/shift': typeof AppShiftRoute
  '/account-restricted': typeof PublicAccountRestrictedRoute
  '/biometric-unlock': typeof PublicBiometricUnlockRoute
  '/company-select': typeof PublicCompanySelectRoute
  '/depot-select': typeof PublicDepotSelectRoute
  '/initial-sync': typeof PublicInitialSyncRoute
  '/mfa': typeof PublicMfaRoute
  '/sign-in': typeof PublicSignInRoute
  '/splash': typeof PublicSplashRoute
  '/update-required': typeof PublicUpdateRequiredRoute
  '/checks/$checkId': typeof AppChecksCheckIdRoute
  '/defects/$defectId': typeof AppDefectsDefectIdRoute
  '/inspections/analytics': typeof AppInspectionsAnalyticsRoute
  '/inspections/damage-review': typeof AppInspectionsDamageReviewRoute
  '/inspections/repair-verification': typeof AppInspectionsRepairVerificationRoute
  '/more/about': typeof AppMoreAboutRoute
  '/more/account': typeof AppMoreAccountRoute
  '/more/bodywork': typeof AppMoreBodyworkRoute
  '/more/messages': typeof AppMoreMessagesRoute
  '/more/settings': typeof AppMoreSettingsRoute
  '/more/sync': typeof AppMoreSyncRoute
  '/more/vehicle-checks': typeof AppMoreVehicleChecksRoute
  '/simulate/driver-report': typeof AppSimulateDriverReportRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/vor/$caseId': typeof AppVorCaseIdRoute
  '/yard/map': typeof AppYardMapRoute
  '/welcome/$step': typeof PublicWelcomeStepRoute
  '/checks': typeof AppChecksIndexRoute
  '/defects': typeof AppDefectsIndexRoute
  '/inspections': typeof AppInspectionsIndexRoute
  '/more': typeof AppMoreIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/vor': typeof AppVorIndexRoute
  '/yard': typeof AppYardIndexRoute
  '/yard/$vehicleId/check': typeof AppYardVehicleIdCheckRoute
  '/yard/$vehicleId/condition': typeof AppYardVehicleIdConditionRouteWithChildren
  '/yard/$vehicleId/equipment': typeof AppYardVehicleIdEquipmentRoute
  '/api/v1/yard/bootstrap': typeof ApiV1YardBootstrapRoute
  '/api/v1/yard/health': typeof ApiV1YardHealthRoute
  '/api/v1/yard/mutations': typeof ApiV1YardMutationsRoute
  '/yard/$vehicleId': typeof AppYardVehicleIdIndexRoute
  '/yard/$vehicleId/adblue/refill': typeof AppYardVehicleIdAdblueRefillRoute
  '/yard/$vehicleId/condition/compare': typeof AppYardVehicleIdConditionCompareRoute
  '/yard/$vehicleId/condition/inspect': typeof AppYardVehicleIdConditionInspectRoute
  '/yard/$vehicleId/condition/damage/$damageId': typeof AppYardVehicleIdConditionDamageDamageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/arrivals': typeof AppArrivalsRoute
  '/_app/checks': typeof AppChecksRouteWithChildren
  '/_app/defects': typeof AppDefectsRouteWithChildren
  '/_app/departure-line': typeof AppDepartureLineRoute
  '/_app/inspections': typeof AppInspectionsRouteWithChildren
  '/_app/more': typeof AppMoreRouteWithChildren
  '/_app/movements': typeof AppMovementsRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/shift': typeof AppShiftRoute
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/_app/vor': typeof AppVorRouteWithChildren
  '/_app/yard': typeof AppYardRouteWithChildren
  '/_public/account-restricted': typeof PublicAccountRestrictedRoute
  '/_public/biometric-unlock': typeof PublicBiometricUnlockRoute
  '/_public/company-select': typeof PublicCompanySelectRoute
  '/_public/depot-select': typeof PublicDepotSelectRoute
  '/_public/initial-sync': typeof PublicInitialSyncRoute
  '/_public/mfa': typeof PublicMfaRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/splash': typeof PublicSplashRoute
  '/_public/update-required': typeof PublicUpdateRequiredRoute
  '/_app/': typeof AppIndexRoute
  '/_app/checks/$checkId': typeof AppChecksCheckIdRoute
  '/_app/defects/$defectId': typeof AppDefectsDefectIdRoute
  '/_app/inspections/analytics': typeof AppInspectionsAnalyticsRoute
  '/_app/inspections/damage-review': typeof AppInspectionsDamageReviewRoute
  '/_app/inspections/repair-verification': typeof AppInspectionsRepairVerificationRoute
  '/_app/more/about': typeof AppMoreAboutRoute
  '/_app/more/account': typeof AppMoreAccountRoute
  '/_app/more/bodywork': typeof AppMoreBodyworkRoute
  '/_app/more/messages': typeof AppMoreMessagesRoute
  '/_app/more/settings': typeof AppMoreSettingsRoute
  '/_app/more/sync': typeof AppMoreSyncRoute
  '/_app/more/vehicle-checks': typeof AppMoreVehicleChecksRoute
  '/_app/simulate/driver-report': typeof AppSimulateDriverReportRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/vor/$caseId': typeof AppVorCaseIdRoute
  '/_app/yard/$vehicleId': typeof AppYardVehicleIdRouteWithChildren
  '/_app/yard/map': typeof AppYardMapRoute
  '/_public/welcome/$step': typeof PublicWelcomeStepRoute
  '/_app/checks/': typeof AppChecksIndexRoute
  '/_app/defects/': typeof AppDefectsIndexRoute
  '/_app/inspections/': typeof AppInspectionsIndexRoute
  '/_app/more/': typeof AppMoreIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/vor/': typeof AppVorIndexRoute
  '/_app/yard/': typeof AppYardIndexRoute
  '/_app/yard/$vehicleId/check': typeof AppYardVehicleIdCheckRoute
  '/_app/yard/$vehicleId/condition': typeof AppYardVehicleIdConditionRouteWithChildren
  '/_app/yard/$vehicleId/equipment': typeof AppYardVehicleIdEquipmentRoute
  '/api/v1/yard/bootstrap': typeof ApiV1YardBootstrapRoute
  '/api/v1/yard/health': typeof ApiV1YardHealthRoute
  '/api/v1/yard/mutations': typeof ApiV1YardMutationsRoute
  '/_app/yard/$vehicleId/': typeof AppYardVehicleIdIndexRoute
  '/_app/yard/$vehicleId/adblue/refill': typeof AppYardVehicleIdAdblueRefillRoute
  '/_app/yard/$vehicleId/condition/compare': typeof AppYardVehicleIdConditionCompareRoute
  '/_app/yard/$vehicleId/condition/inspect': typeof AppYardVehicleIdConditionInspectRoute
  '/_app/yard/$vehicleId/condition/damage/$damageId': typeof AppYardVehicleIdConditionDamageDamageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrivals'
    | '/checks'
    | '/defects'
    | '/departure-line'
    | '/inspections'
    | '/more'
    | '/movements'
    | '/scan'
    | '/shift'
    | '/tasks'
    | '/vor'
    | '/yard'
    | '/account-restricted'
    | '/biometric-unlock'
    | '/company-select'
    | '/depot-select'
    | '/initial-sync'
    | '/mfa'
    | '/sign-in'
    | '/splash'
    | '/update-required'
    | '/checks/$checkId'
    | '/defects/$defectId'
    | '/inspections/analytics'
    | '/inspections/damage-review'
    | '/inspections/repair-verification'
    | '/more/about'
    | '/more/account'
    | '/more/bodywork'
    | '/more/messages'
    | '/more/settings'
    | '/more/sync'
    | '/more/vehicle-checks'
    | '/simulate/driver-report'
    | '/tasks/$taskId'
    | '/vor/$caseId'
    | '/yard/$vehicleId'
    | '/yard/map'
    | '/welcome/$step'
    | '/checks/'
    | '/defects/'
    | '/inspections/'
    | '/more/'
    | '/tasks/'
    | '/vor/'
    | '/yard/'
    | '/yard/$vehicleId/check'
    | '/yard/$vehicleId/condition'
    | '/yard/$vehicleId/equipment'
    | '/api/v1/yard/bootstrap'
    | '/api/v1/yard/health'
    | '/api/v1/yard/mutations'
    | '/yard/$vehicleId/'
    | '/yard/$vehicleId/adblue/refill'
    | '/yard/$vehicleId/condition/compare'
    | '/yard/$vehicleId/condition/inspect'
    | '/yard/$vehicleId/condition/damage/$damageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrivals'
    | '/departure-line'
    | '/movements'
    | '/scan'
    | '/shift'
    | '/account-restricted'
    | '/biometric-unlock'
    | '/company-select'
    | '/depot-select'
    | '/initial-sync'
    | '/mfa'
    | '/sign-in'
    | '/splash'
    | '/update-required'
    | '/checks/$checkId'
    | '/defects/$defectId'
    | '/inspections/analytics'
    | '/inspections/damage-review'
    | '/inspections/repair-verification'
    | '/more/about'
    | '/more/account'
    | '/more/bodywork'
    | '/more/messages'
    | '/more/settings'
    | '/more/sync'
    | '/more/vehicle-checks'
    | '/simulate/driver-report'
    | '/tasks/$taskId'
    | '/vor/$caseId'
    | '/yard/map'
    | '/welcome/$step'
    | '/checks'
    | '/defects'
    | '/inspections'
    | '/more'
    | '/tasks'
    | '/vor'
    | '/yard'
    | '/yard/$vehicleId/check'
    | '/yard/$vehicleId/condition'
    | '/yard/$vehicleId/equipment'
    | '/api/v1/yard/bootstrap'
    | '/api/v1/yard/health'
    | '/api/v1/yard/mutations'
    | '/yard/$vehicleId'
    | '/yard/$vehicleId/adblue/refill'
    | '/yard/$vehicleId/condition/compare'
    | '/yard/$vehicleId/condition/inspect'
    | '/yard/$vehicleId/condition/damage/$damageId'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/arrivals'
    | '/_app/checks'
    | '/_app/defects'
    | '/_app/departure-line'
    | '/_app/inspections'
    | '/_app/more'
    | '/_app/movements'
    | '/_app/scan'
    | '/_app/shift'
    | '/_app/tasks'
    | '/_app/vor'
    | '/_app/yard'
    | '/_public/account-restricted'
    | '/_public/biometric-unlock'
    | '/_public/company-select'
    | '/_public/depot-select'
    | '/_public/initial-sync'
    | '/_public/mfa'
    | '/_public/sign-in'
    | '/_public/splash'
    | '/_public/update-required'
    | '/_app/'
    | '/_app/checks/$checkId'
    | '/_app/defects/$defectId'
    | '/_app/inspections/analytics'
    | '/_app/inspections/damage-review'
    | '/_app/inspections/repair-verification'
    | '/_app/more/about'
    | '/_app/more/account'
    | '/_app/more/bodywork'
    | '/_app/more/messages'
    | '/_app/more/settings'
    | '/_app/more/sync'
    | '/_app/more/vehicle-checks'
    | '/_app/simulate/driver-report'
    | '/_app/tasks/$taskId'
    | '/_app/vor/$caseId'
    | '/_app/yard/$vehicleId'
    | '/_app/yard/map'
    | '/_public/welcome/$step'
    | '/_app/checks/'
    | '/_app/defects/'
    | '/_app/inspections/'
    | '/_app/more/'
    | '/_app/tasks/'
    | '/_app/vor/'
    | '/_app/yard/'
    | '/_app/yard/$vehicleId/check'
    | '/_app/yard/$vehicleId/condition'
    | '/_app/yard/$vehicleId/equipment'
    | '/api/v1/yard/bootstrap'
    | '/api/v1/yard/health'
    | '/api/v1/yard/mutations'
    | '/_app/yard/$vehicleId/'
    | '/_app/yard/$vehicleId/adblue/refill'
    | '/_app/yard/$vehicleId/condition/compare'
    | '/_app/yard/$vehicleId/condition/inspect'
    | '/_app/yard/$vehicleId/condition/damage/$damageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiV1YardBootstrapRoute: typeof ApiV1YardBootstrapRoute
  ApiV1YardHealthRoute: typeof ApiV1YardHealthRoute
  ApiV1YardMutationsRoute: typeof ApiV1YardMutationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/update-required': {
      id: '/_public/update-required'
      path: '/update-required'
      fullPath: '/update-required'
      preLoaderRoute: typeof PublicUpdateRequiredRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/splash': {
      id: '/_public/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof PublicSplashRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/mfa': {
      id: '/_public/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof PublicMfaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/initial-sync': {
      id: '/_public/initial-sync'
      path: '/initial-sync'
      fullPath: '/initial-sync'
      preLoaderRoute: typeof PublicInitialSyncRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/depot-select': {
      id: '/_public/depot-select'
      path: '/depot-select'
      fullPath: '/depot-select'
      preLoaderRoute: typeof PublicDepotSelectRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/company-select': {
      id: '/_public/company-select'
      path: '/company-select'
      fullPath: '/company-select'
      preLoaderRoute: typeof PublicCompanySelectRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/biometric-unlock': {
      id: '/_public/biometric-unlock'
      path: '/biometric-unlock'
      fullPath: '/biometric-unlock'
      preLoaderRoute: typeof PublicBiometricUnlockRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/account-restricted': {
      id: '/_public/account-restricted'
      path: '/account-restricted'
      fullPath: '/account-restricted'
      preLoaderRoute: typeof PublicAccountRestrictedRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/yard': {
      id: '/_app/yard'
      path: '/yard'
      fullPath: '/yard'
      preLoaderRoute: typeof AppYardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vor': {
      id: '/_app/vor'
      path: '/vor'
      fullPath: '/vor'
      preLoaderRoute: typeof AppVorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shift': {
      id: '/_app/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof AppShiftRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movements': {
      id: '/_app/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspections': {
      id: '/_app/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departure-line': {
      id: '/_app/departure-line'
      path: '/departure-line'
      fullPath: '/departure-line'
      preLoaderRoute: typeof AppDepartureLineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/defects': {
      id: '/_app/defects'
      path: '/defects'
      fullPath: '/defects'
      preLoaderRoute: typeof AppDefectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checks': {
      id: '/_app/checks'
      path: '/checks'
      fullPath: '/checks'
      preLoaderRoute: typeof AppChecksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arrivals': {
      id: '/_app/arrivals'
      path: '/arrivals'
      fullPath: '/arrivals'
      preLoaderRoute: typeof AppArrivalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yard/': {
      id: '/_app/yard/'
      path: '/'
      fullPath: '/yard/'
      preLoaderRoute: typeof AppYardIndexRouteImport
      parentRoute: typeof AppYardRoute
    }
    '/_app/vor/': {
      id: '/_app/vor/'
      path: '/'
      fullPath: '/vor/'
      preLoaderRoute: typeof AppVorIndexRouteImport
      parentRoute: typeof AppVorRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/more/': {
      id: '/_app/more/'
      path: '/'
      fullPath: '/more/'
      preLoaderRoute: typeof AppMoreIndexRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/inspections/': {
      id: '/_app/inspections/'
      path: '/'
      fullPath: '/inspections/'
      preLoaderRoute: typeof AppInspectionsIndexRouteImport
      parentRoute: typeof AppInspectionsRoute
    }
    '/_app/defects/': {
      id: '/_app/defects/'
      path: '/'
      fullPath: '/defects/'
      preLoaderRoute: typeof AppDefectsIndexRouteImport
      parentRoute: typeof AppDefectsRoute
    }
    '/_app/checks/': {
      id: '/_app/checks/'
      path: '/'
      fullPath: '/checks/'
      preLoaderRoute: typeof AppChecksIndexRouteImport
      parentRoute: typeof AppChecksRoute
    }
    '/_public/welcome/$step': {
      id: '/_public/welcome/$step'
      path: '/welcome/$step'
      fullPath: '/welcome/$step'
      preLoaderRoute: typeof PublicWelcomeStepRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/yard/map': {
      id: '/_app/yard/map'
      path: '/map'
      fullPath: '/yard/map'
      preLoaderRoute: typeof AppYardMapRouteImport
      parentRoute: typeof AppYardRoute
    }
    '/_app/yard/$vehicleId': {
      id: '/_app/yard/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/yard/$vehicleId'
      preLoaderRoute: typeof AppYardVehicleIdRouteImport
      parentRoute: typeof AppYardRoute
    }
    '/_app/vor/$caseId': {
      id: '/_app/vor/$caseId'
      path: '/$caseId'
      fullPath: '/vor/$caseId'
      preLoaderRoute: typeof AppVorCaseIdRouteImport
      parentRoute: typeof AppVorRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/simulate/driver-report': {
      id: '/_app/simulate/driver-report'
      path: '/simulate/driver-report'
      fullPath: '/simulate/driver-report'
      preLoaderRoute: typeof AppSimulateDriverReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more/vehicle-checks': {
      id: '/_app/more/vehicle-checks'
      path: '/vehicle-checks'
      fullPath: '/more/vehicle-checks'
      preLoaderRoute: typeof AppMoreVehicleChecksRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/sync': {
      id: '/_app/more/sync'
      path: '/sync'
      fullPath: '/more/sync'
      preLoaderRoute: typeof AppMoreSyncRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/settings': {
      id: '/_app/more/settings'
      path: '/settings'
      fullPath: '/more/settings'
      preLoaderRoute: typeof AppMoreSettingsRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/messages': {
      id: '/_app/more/messages'
      path: '/messages'
      fullPath: '/more/messages'
      preLoaderRoute: typeof AppMoreMessagesRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/bodywork': {
      id: '/_app/more/bodywork'
      path: '/bodywork'
      fullPath: '/more/bodywork'
      preLoaderRoute: typeof AppMoreBodyworkRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/account': {
      id: '/_app/more/account'
      path: '/account'
      fullPath: '/more/account'
      preLoaderRoute: typeof AppMoreAccountRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/about': {
      id: '/_app/more/about'
      path: '/about'
      fullPath: '/more/about'
      preLoaderRoute: typeof AppMoreAboutRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/inspections/repair-verification': {
      id: '/_app/inspections/repair-verification'
      path: '/repair-verification'
      fullPath: '/inspections/repair-verification'
      preLoaderRoute: typeof AppInspectionsRepairVerificationRouteImport
      parentRoute: typeof AppInspectionsRoute
    }
    '/_app/inspections/damage-review': {
      id: '/_app/inspections/damage-review'
      path: '/damage-review'
      fullPath: '/inspections/damage-review'
      preLoaderRoute: typeof AppInspectionsDamageReviewRouteImport
      parentRoute: typeof AppInspectionsRoute
    }
    '/_app/inspections/analytics': {
      id: '/_app/inspections/analytics'
      path: '/analytics'
      fullPath: '/inspections/analytics'
      preLoaderRoute: typeof AppInspectionsAnalyticsRouteImport
      parentRoute: typeof AppInspectionsRoute
    }
    '/_app/defects/$defectId': {
      id: '/_app/defects/$defectId'
      path: '/$defectId'
      fullPath: '/defects/$defectId'
      preLoaderRoute: typeof AppDefectsDefectIdRouteImport
      parentRoute: typeof AppDefectsRoute
    }
    '/_app/checks/$checkId': {
      id: '/_app/checks/$checkId'
      path: '/$checkId'
      fullPath: '/checks/$checkId'
      preLoaderRoute: typeof AppChecksCheckIdRouteImport
      parentRoute: typeof AppChecksRoute
    }
    '/_app/yard/$vehicleId/': {
      id: '/_app/yard/$vehicleId/'
      path: '/'
      fullPath: '/yard/$vehicleId/'
      preLoaderRoute: typeof AppYardVehicleIdIndexRouteImport
      parentRoute: typeof AppYardVehicleIdRoute
    }
    '/api/v1/yard/mutations': {
      id: '/api/v1/yard/mutations'
      path: '/api/v1/yard/mutations'
      fullPath: '/api/v1/yard/mutations'
      preLoaderRoute: typeof ApiV1YardMutationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/yard/health': {
      id: '/api/v1/yard/health'
      path: '/api/v1/yard/health'
      fullPath: '/api/v1/yard/health'
      preLoaderRoute: typeof ApiV1YardHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/yard/bootstrap': {
      id: '/api/v1/yard/bootstrap'
      path: '/api/v1/yard/bootstrap'
      fullPath: '/api/v1/yard/bootstrap'
      preLoaderRoute: typeof ApiV1YardBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/yard/$vehicleId/equipment': {
      id: '/_app/yard/$vehicleId/equipment'
      path: '/equipment'
      fullPath: '/yard/$vehicleId/equipment'
      preLoaderRoute: typeof AppYardVehicleIdEquipmentRouteImport
      parentRoute: typeof AppYardVehicleIdRoute
    }
    '/_app/yard/$vehicleId/condition': {
      id: '/_app/yard/$vehicleId/condition'
      path: '/condition'
      fullPath: '/yard/$vehicleId/condition'
      preLoaderRoute: typeof AppYardVehicleIdConditionRouteImport
      parentRoute: typeof AppYardVehicleIdRoute
    }
    '/_app/yard/$vehicleId/check': {
      id: '/_app/yard/$vehicleId/check'
      path: '/check'
      fullPath: '/yard/$vehicleId/check'
      preLoaderRoute: typeof AppYardVehicleIdCheckRouteImport
      parentRoute: typeof AppYardVehicleIdRoute
    }
    '/_app/yard/$vehicleId/condition/inspect': {
      id: '/_app/yard/$vehicleId/condition/inspect'
      path: '/inspect'
      fullPath: '/yard/$vehicleId/condition/inspect'
      preLoaderRoute: typeof AppYardVehicleIdConditionInspectRouteImport
      parentRoute: typeof AppYardVehicleIdConditionRoute
    }
    '/_app/yard/$vehicleId/condition/compare': {
      id: '/_app/yard/$vehicleId/condition/compare'
      path: '/compare'
      fullPath: '/yard/$vehicleId/condition/compare'
      preLoaderRoute: typeof AppYardVehicleIdConditionCompareRouteImport
      parentRoute: typeof AppYardVehicleIdConditionRoute
    }
    '/_app/yard/$vehicleId/adblue/refill': {
      id: '/_app/yard/$vehicleId/adblue/refill'
      path: '/adblue/refill'
      fullPath: '/yard/$vehicleId/adblue/refill'
      preLoaderRoute: typeof AppYardVehicleIdAdblueRefillRouteImport
      parentRoute: typeof AppYardVehicleIdRoute
    }
    '/_app/yard/$vehicleId/condition/damage/$damageId': {
      id: '/_app/yard/$vehicleId/condition/damage/$damageId'
      path: '/damage/$damageId'
      fullPath: '/yard/$vehicleId/condition/damage/$damageId'
      preLoaderRoute: typeof AppYardVehicleIdConditionDamageDamageIdRouteImport
      parentRoute: typeof AppYardVehicleIdConditionRoute
    }
  }
}

interface AppChecksRouteChildren {
  AppChecksCheckIdRoute: typeof AppChecksCheckIdRoute
  AppChecksIndexRoute: typeof AppChecksIndexRoute
}

const AppChecksRouteChildren: AppChecksRouteChildren = {
  AppChecksCheckIdRoute: AppChecksCheckIdRoute,
  AppChecksIndexRoute: AppChecksIndexRoute,
}

const AppChecksRouteWithChildren = AppChecksRoute._addFileChildren(
  AppChecksRouteChildren,
)

interface AppDefectsRouteChildren {
  AppDefectsDefectIdRoute: typeof AppDefectsDefectIdRoute
  AppDefectsIndexRoute: typeof AppDefectsIndexRoute
}

const AppDefectsRouteChildren: AppDefectsRouteChildren = {
  AppDefectsDefectIdRoute: AppDefectsDefectIdRoute,
  AppDefectsIndexRoute: AppDefectsIndexRoute,
}

const AppDefectsRouteWithChildren = AppDefectsRoute._addFileChildren(
  AppDefectsRouteChildren,
)

interface AppInspectionsRouteChildren {
  AppInspectionsAnalyticsRoute: typeof AppInspectionsAnalyticsRoute
  AppInspectionsDamageReviewRoute: typeof AppInspectionsDamageReviewRoute
  AppInspectionsRepairVerificationRoute: typeof AppInspectionsRepairVerificationRoute
  AppInspectionsIndexRoute: typeof AppInspectionsIndexRoute
}

const AppInspectionsRouteChildren: AppInspectionsRouteChildren = {
  AppInspectionsAnalyticsRoute: AppInspectionsAnalyticsRoute,
  AppInspectionsDamageReviewRoute: AppInspectionsDamageReviewRoute,
  AppInspectionsRepairVerificationRoute: AppInspectionsRepairVerificationRoute,
  AppInspectionsIndexRoute: AppInspectionsIndexRoute,
}

const AppInspectionsRouteWithChildren = AppInspectionsRoute._addFileChildren(
  AppInspectionsRouteChildren,
)

interface AppMoreRouteChildren {
  AppMoreAboutRoute: typeof AppMoreAboutRoute
  AppMoreAccountRoute: typeof AppMoreAccountRoute
  AppMoreBodyworkRoute: typeof AppMoreBodyworkRoute
  AppMoreMessagesRoute: typeof AppMoreMessagesRoute
  AppMoreSettingsRoute: typeof AppMoreSettingsRoute
  AppMoreSyncRoute: typeof AppMoreSyncRoute
  AppMoreVehicleChecksRoute: typeof AppMoreVehicleChecksRoute
  AppMoreIndexRoute: typeof AppMoreIndexRoute
}

const AppMoreRouteChildren: AppMoreRouteChildren = {
  AppMoreAboutRoute: AppMoreAboutRoute,
  AppMoreAccountRoute: AppMoreAccountRoute,
  AppMoreBodyworkRoute: AppMoreBodyworkRoute,
  AppMoreMessagesRoute: AppMoreMessagesRoute,
  AppMoreSettingsRoute: AppMoreSettingsRoute,
  AppMoreSyncRoute: AppMoreSyncRoute,
  AppMoreVehicleChecksRoute: AppMoreVehicleChecksRoute,
  AppMoreIndexRoute: AppMoreIndexRoute,
}

const AppMoreRouteWithChildren =
  AppMoreRoute._addFileChildren(AppMoreRouteChildren)

interface AppTasksRouteChildren {
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppVorRouteChildren {
  AppVorCaseIdRoute: typeof AppVorCaseIdRoute
  AppVorIndexRoute: typeof AppVorIndexRoute
}

const AppVorRouteChildren: AppVorRouteChildren = {
  AppVorCaseIdRoute: AppVorCaseIdRoute,
  AppVorIndexRoute: AppVorIndexRoute,
}

const AppVorRouteWithChildren =
  AppVorRoute._addFileChildren(AppVorRouteChildren)

interface AppYardVehicleIdConditionRouteChildren {
  AppYardVehicleIdConditionCompareRoute: typeof AppYardVehicleIdConditionCompareRoute
  AppYardVehicleIdConditionInspectRoute: typeof AppYardVehicleIdConditionInspectRoute
  AppYardVehicleIdConditionDamageDamageIdRoute: typeof AppYardVehicleIdConditionDamageDamageIdRoute
}

const AppYardVehicleIdConditionRouteChildren: AppYardVehicleIdConditionRouteChildren =
  {
    AppYardVehicleIdConditionCompareRoute:
      AppYardVehicleIdConditionCompareRoute,
    AppYardVehicleIdConditionInspectRoute:
      AppYardVehicleIdConditionInspectRoute,
    AppYardVehicleIdConditionDamageDamageIdRoute:
      AppYardVehicleIdConditionDamageDamageIdRoute,
  }

const AppYardVehicleIdConditionRouteWithChildren =
  AppYardVehicleIdConditionRoute._addFileChildren(
    AppYardVehicleIdConditionRouteChildren,
  )

interface AppYardVehicleIdRouteChildren {
  AppYardVehicleIdCheckRoute: typeof AppYardVehicleIdCheckRoute
  AppYardVehicleIdConditionRoute: typeof AppYardVehicleIdConditionRouteWithChildren
  AppYardVehicleIdEquipmentRoute: typeof AppYardVehicleIdEquipmentRoute
  AppYardVehicleIdIndexRoute: typeof AppYardVehicleIdIndexRoute
  AppYardVehicleIdAdblueRefillRoute: typeof AppYardVehicleIdAdblueRefillRoute
}

const AppYardVehicleIdRouteChildren: AppYardVehicleIdRouteChildren = {
  AppYardVehicleIdCheckRoute: AppYardVehicleIdCheckRoute,
  AppYardVehicleIdConditionRoute: AppYardVehicleIdConditionRouteWithChildren,
  AppYardVehicleIdEquipmentRoute: AppYardVehicleIdEquipmentRoute,
  AppYardVehicleIdIndexRoute: AppYardVehicleIdIndexRoute,
  AppYardVehicleIdAdblueRefillRoute: AppYardVehicleIdAdblueRefillRoute,
}

const AppYardVehicleIdRouteWithChildren =
  AppYardVehicleIdRoute._addFileChildren(AppYardVehicleIdRouteChildren)

interface AppYardRouteChildren {
  AppYardVehicleIdRoute: typeof AppYardVehicleIdRouteWithChildren
  AppYardMapRoute: typeof AppYardMapRoute
  AppYardIndexRoute: typeof AppYardIndexRoute
}

const AppYardRouteChildren: AppYardRouteChildren = {
  AppYardVehicleIdRoute: AppYardVehicleIdRouteWithChildren,
  AppYardMapRoute: AppYardMapRoute,
  AppYardIndexRoute: AppYardIndexRoute,
}

const AppYardRouteWithChildren =
  AppYardRoute._addFileChildren(AppYardRouteChildren)

interface AppRouteChildren {
  AppArrivalsRoute: typeof AppArrivalsRoute
  AppChecksRoute: typeof AppChecksRouteWithChildren
  AppDefectsRoute: typeof AppDefectsRouteWithChildren
  AppDepartureLineRoute: typeof AppDepartureLineRoute
  AppInspectionsRoute: typeof AppInspectionsRouteWithChildren
  AppMoreRoute: typeof AppMoreRouteWithChildren
  AppMovementsRoute: typeof AppMovementsRoute
  AppScanRoute: typeof AppScanRoute
  AppShiftRoute: typeof AppShiftRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppVorRoute: typeof AppVorRouteWithChildren
  AppYardRoute: typeof AppYardRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppSimulateDriverReportRoute: typeof AppSimulateDriverReportRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArrivalsRoute: AppArrivalsRoute,
  AppChecksRoute: AppChecksRouteWithChildren,
  AppDefectsRoute: AppDefectsRouteWithChildren,
  AppDepartureLineRoute: AppDepartureLineRoute,
  AppInspectionsRoute: AppInspectionsRouteWithChildren,
  AppMoreRoute: AppMoreRouteWithChildren,
  AppMovementsRoute: AppMovementsRoute,
  AppScanRoute: AppScanRoute,
  AppShiftRoute: AppShiftRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppVorRoute: AppVorRouteWithChildren,
  AppYardRoute: AppYardRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppSimulateDriverReportRoute: AppSimulateDriverReportRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAccountRestrictedRoute: typeof PublicAccountRestrictedRoute
  PublicBiometricUnlockRoute: typeof PublicBiometricUnlockRoute
  PublicCompanySelectRoute: typeof PublicCompanySelectRoute
  PublicDepotSelectRoute: typeof PublicDepotSelectRoute
  PublicInitialSyncRoute: typeof PublicInitialSyncRoute
  PublicMfaRoute: typeof PublicMfaRoute
  PublicSignInRoute: typeof PublicSignInRoute
  PublicSplashRoute: typeof PublicSplashRoute
  PublicUpdateRequiredRoute: typeof PublicUpdateRequiredRoute
  PublicWelcomeStepRoute: typeof PublicWelcomeStepRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAccountRestrictedRoute: PublicAccountRestrictedRoute,
  PublicBiometricUnlockRoute: PublicBiometricUnlockRoute,
  PublicCompanySelectRoute: PublicCompanySelectRoute,
  PublicDepotSelectRoute: PublicDepotSelectRoute,
  PublicInitialSyncRoute: PublicInitialSyncRoute,
  PublicMfaRoute: PublicMfaRoute,
  PublicSignInRoute: PublicSignInRoute,
  PublicSplashRoute: PublicSplashRoute,
  PublicUpdateRequiredRoute: PublicUpdateRequiredRoute,
  PublicWelcomeStepRoute: PublicWelcomeStepRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiV1YardBootstrapRoute: ApiV1YardBootstrapRoute,
  ApiV1YardHealthRoute: ApiV1YardHealthRoute,
  ApiV1YardMutationsRoute: ApiV1YardMutationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
