import { DEFAULT_FLEET_RESOURCES_SETTINGS } from './constants'
import type {
  BudgetLine,
  DepotStockRow,
  EquipmentAsset,
  FuelCardRecord,
  PurchaseRequestRow,
  ResourceCatalogueItem,
  ResourceIntegration,
  ResourceTransaction,
  StockTransferRow,
  TyreAsset,
  WholeLifeCostRow,
} from './types'

const hoursAgo = (n: number) => new Date(Date.now() - n * 60 * 60 * 1000).toISOString()
const daysAgo = (n: number) => new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString()

export const RESOURCE_CATALOGUE: ResourceCatalogueItem[] = [
  {
    id: 'res-diesel',
    category: 'fuel',
    sku: 'FUEL-DSL',
    name: 'Diesel',
    unit: 'L',
    safetyCritical: false,
    reorderLevel: 0,
    compatibleVehicleClasses: ['minibus', 'coach', 'van'],
  },
  {
    id: 'res-adblue',
    category: 'adblue',
    sku: 'FLUID-ADBLUE',
    name: 'AdBlue',
    unit: 'L',
    safetyCritical: false,
    reorderLevel: 40,
    compatibleVehicleClasses: ['minibus', 'coach'],
  },
  {
    id: 'res-oil-5w30',
    category: 'fluid',
    sku: 'FLUID-OIL-5W30',
    name: 'Engine oil 5W-30',
    unit: 'L',
    safetyCritical: false,
    reorderLevel: 20,
    compatibleVehicleClasses: ['minibus', 'van'],
  },
  {
    id: 'res-coolant',
    category: 'fluid',
    sku: 'FLUID-COOLANT',
    name: 'Coolant',
    unit: 'L',
    safetyCritical: false,
    reorderLevel: 15,
    compatibleVehicleClasses: ['minibus', 'coach', 'van'],
  },
  {
    id: 'res-screenwash',
    category: 'fluid',
    sku: 'FLUID-WASH',
    name: 'Screenwash',
    unit: 'L',
    safetyCritical: false,
    reorderLevel: 10,
    compatibleVehicleClasses: ['minibus', 'coach', 'van'],
  },
  {
    id: 'res-brake-fluid',
    category: 'fluid',
    sku: 'FLUID-BRAKE',
    name: 'Brake fluid DOT 4',
    unit: 'L',
    safetyCritical: true,
    reorderLevel: 8,
    compatibleVehicleClasses: ['minibus', 'coach', 'van'],
  },
  {
    id: 'res-wiper',
    category: 'consumable',
    sku: 'CONS-WIPER',
    name: 'Wiper blades (pair)',
    unit: 'pair',
    safetyCritical: false,
    reorderLevel: 6,
    compatibleVehicleClasses: ['minibus', 'coach', 'van'],
  },
  {
    id: 'res-tyre-215',
    category: 'tyre',
    sku: 'TYRE-215-75R16',
    name: 'Tyre 215/75R16C',
    unit: 'each',
    safetyCritical: true,
    reorderLevel: 4,
    compatibleVehicleClasses: ['minibus', 'van'],
  },
  {
    id: 'res-first-aid',
    category: 'safety_equipment',
    sku: 'SAFE-FIRSTAID',
    name: 'First aid kit',
    unit: 'each',
    safetyCritical: true,
    reorderLevel: 2,
    compatibleVehicleClasses: ['minibus', 'coach', 'van'],
  },
  {
    id: 'res-wc-restraint',
    category: 'accessibility_equipment',
    sku: 'ACC-WC-REST',
    name: 'Wheelchair restraint set',
    unit: 'each',
    safetyCritical: true,
    reorderLevel: 2,
    compatibleVehicleClasses: ['minibus', 'coach'],
  },
]

export function createFleetResourcesSeed(): {
  catalogue: ResourceCatalogueItem[]
  transactions: ResourceTransaction[]
  stock: DepotStockRow[]
  cards: FuelCardRecord[]
  purchaseRequests: PurchaseRequestRow[]
  tyres: TyreAsset[]
  equipment: EquipmentAsset[]
  stockTransfers: StockTransferRow[]
  integrations: ResourceIntegration[]
  budgets: BudgetLine[]
  wholeLife: WholeLifeCostRow[]
  settings: typeof DEFAULT_FLEET_RESOURCES_SETTINGS
} {
  const transactions: ResourceTransaction[] = [
    {
      id: 'rtx-fuel-1',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceCategory: 'fuel',
      resourceItemId: 'res-diesel',
      resourceName: 'Diesel',
      transactionType: 'top_up',
      quantity: 62,
      unit: 'L',
      unitPrice: 1.48,
      vatAmount: 17.5,
      grossAmount: 91.76,
      vehicleId: 'veh-1',
      registrationNumber: 'AB12 CDE',
      driverId: 'drv-1',
      driverName: 'Jane Smith',
      staffName: null,
      supplierName: 'Shell Wembley',
      workOrderId: null,
      defectId: null,
      odometer: 84120,
      fuelLevelBefore: 28,
      fuelLevelAfter: 95,
      fullTank: true,
      receiptFileName: 'shell-receipt-84120.jpg',
      fuelCardId: 'card-1',
      status: 'approved',
      anomalyFlags: [],
      notes: null,
      createdAt: daysAgo(2),
      createdBy: 'Jane Smith',
      approvedBy: 'Tom Harris',
    },
    {
      id: 'rtx-fuel-2',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceCategory: 'fuel',
      resourceItemId: 'res-diesel',
      resourceName: 'Diesel',
      transactionType: 'top_up',
      quantity: 88,
      unit: 'L',
      unitPrice: 1.49,
      vatAmount: 24.8,
      grossAmount: 131.12,
      vehicleId: 'veh-4',
      registrationNumber: 'CD34 EFG',
      driverId: 'drv-2',
      driverName: 'Michael Patel',
      staffName: null,
      supplierName: 'BP Acton',
      workOrderId: null,
      defectId: null,
      odometer: 112380,
      fuelLevelBefore: 15,
      fuelLevelAfter: 90,
      fullTank: true,
      receiptFileName: null,
      fuelCardId: 'card-2',
      status: 'queried',
      anomalyFlags: ['missing_receipt'],
      notes: 'Receipt photo failed to upload',
      createdAt: hoursAgo(6),
      createdBy: 'Michael Patel',
      approvedBy: null,
    },
    {
      id: 'rtx-fuel-3',
      depotId: null,
      depotName: null,
      resourceCategory: 'fuel',
      resourceItemId: 'res-diesel',
      resourceName: 'Diesel',
      transactionType: 'top_up',
      quantity: 210,
      unit: 'L',
      unitPrice: 1.47,
      vatAmount: 58.2,
      grossAmount: 308.7,
      vehicleId: 'veh-2',
      registrationNumber: 'GH56 HIJ',
      driverId: 'drv-3',
      driverName: 'Sarah Khan',
      staffName: null,
      supplierName: 'Esso Northolt',
      workOrderId: null,
      defectId: null,
      odometer: null,
      fuelLevelBefore: 10,
      fuelLevelAfter: 100,
      fullTank: true,
      receiptFileName: 'esso-bulk.jpg',
      fuelCardId: 'card-1',
      status: 'pending_approval',
      anomalyFlags: ['quantity_above_policy', 'missing_odometer'],
      notes: 'Above max litres policy — review capacity',
      createdAt: hoursAgo(3),
      createdBy: 'Sarah Khan',
      approvedBy: null,
    },
    {
      id: 'rtx-adblue-1',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceCategory: 'adblue',
      resourceItemId: 'res-adblue',
      resourceName: 'AdBlue',
      transactionType: 'dispense',
      quantity: 18,
      unit: 'L',
      unitPrice: 0.85,
      vatAmount: 2.91,
      grossAmount: 15.3,
      vehicleId: 'veh-1',
      registrationNumber: 'AB12 CDE',
      driverId: null,
      driverName: null,
      staffName: 'Alice Brown',
      supplierName: null,
      workOrderId: null,
      defectId: null,
      odometer: 84150,
      fuelLevelBefore: null,
      fuelLevelAfter: null,
      fullTank: null,
      receiptFileName: null,
      fuelCardId: null,
      status: 'approved',
      anomalyFlags: [],
      notes: 'Yard dispenser',
      createdAt: daysAgo(1),
      createdBy: 'Alice Brown',
      approvedBy: 'Tom Harris',
    },
    {
      id: 'rtx-oil-1',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceCategory: 'fluid',
      resourceItemId: 'res-oil-5w30',
      resourceName: 'Engine oil 5W-30',
      transactionType: 'issue',
      quantity: 5,
      unit: 'L',
      unitPrice: 8.5,
      vatAmount: 8.5,
      grossAmount: 42.5,
      vehicleId: 'veh-4',
      registrationNumber: 'CD34 EFG',
      driverId: null,
      driverName: null,
      staffName: 'Dave Wilson',
      supplierName: null,
      workOrderId: 'wo-4',
      defectId: null,
      odometer: 112400,
      fuelLevelBefore: null,
      fuelLevelAfter: null,
      fullTank: null,
      receiptFileName: null,
      fuelCardId: null,
      status: 'approved',
      anomalyFlags: [],
      notes: 'Issued to brake WO',
      createdAt: daysAgo(0),
      createdBy: 'Dave Wilson',
      approvedBy: 'Tom Harris',
    },
    {
      id: 'rtx-purchase-1',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceCategory: 'fluid',
      resourceItemId: 'res-adblue',
      resourceName: 'AdBlue',
      transactionType: 'purchase',
      quantity: 200,
      unit: 'L',
      unitPrice: 0.72,
      vatAmount: 28.8,
      grossAmount: 144,
      vehicleId: null,
      registrationNumber: null,
      driverId: null,
      driverName: null,
      staffName: 'Tom Harris',
      supplierName: 'Fleet Fluids Ltd',
      workOrderId: null,
      defectId: null,
      odometer: null,
      fuelLevelBefore: null,
      fuelLevelAfter: null,
      fullTank: null,
      receiptFileName: 'invoice-adblue-4421.pdf',
      fuelCardId: null,
      status: 'reconciled',
      anomalyFlags: [],
      notes: 'Bulk delivery to yard tank',
      createdAt: daysAgo(5),
      createdBy: 'Tom Harris',
      approvedBy: 'Tom Harris',
    },
  ]

  const stock: DepotStockRow[] = [
    {
      id: 'stk-1',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceItemId: 'res-adblue',
      resourceName: 'AdBlue',
      category: 'adblue',
      available: 28,
      reserved: 0,
      minimum: 40,
      unit: 'L',
      status: 'reorder',
    },
    {
      id: 'stk-2',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceItemId: 'res-oil-5w30',
      resourceName: 'Engine oil 5W-30',
      category: 'fluid',
      available: 12,
      reserved: 2,
      minimum: 20,
      unit: 'L',
      status: 'low',
    },
    {
      id: 'stk-3',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceItemId: 'res-coolant',
      resourceName: 'Coolant',
      category: 'fluid',
      available: 45,
      reserved: 0,
      minimum: 15,
      unit: 'L',
      status: 'normal',
    },
    {
      id: 'stk-4',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceItemId: 'res-brake-fluid',
      resourceName: 'Brake fluid DOT 4',
      category: 'fluid',
      available: 3,
      reserved: 1,
      minimum: 8,
      unit: 'L',
      status: 'reorder',
    },
    {
      id: 'stk-5',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceItemId: 'res-screenwash',
      resourceName: 'Screenwash',
      category: 'fluid',
      available: 0,
      reserved: 0,
      minimum: 10,
      unit: 'L',
      status: 'out',
    },
    {
      id: 'stk-6',
      depotId: 'depot-heathrow',
      depotName: 'Heathrow Depot',
      resourceItemId: 'res-adblue',
      resourceName: 'AdBlue',
      category: 'adblue',
      available: 90,
      reserved: 0,
      minimum: 40,
      unit: 'L',
      status: 'normal',
    },
  ]

  const cards: FuelCardRecord[] = [
    {
      id: 'card-1',
      provider: 'Allstar',
      maskedNumber: '•••• 4421',
      status: 'active',
      assignmentModel: 'vehicle',
      assignedVehicleId: 'veh-1',
      assignedRegistration: 'AB12 CDE',
      assignedDriverName: null,
      dailyLimit: 200,
      lastTransactionAt: daysAgo(2),
    },
    {
      id: 'card-2',
      provider: 'Allstar',
      maskedNumber: '•••• 7788',
      status: 'active',
      assignmentModel: 'vehicle',
      assignedVehicleId: 'veh-4',
      assignedRegistration: 'CD34 EFG',
      assignedDriverName: null,
      dailyLimit: 200,
      lastTransactionAt: hoursAgo(6),
    },
    {
      id: 'card-3',
      provider: 'FuelGenie',
      maskedNumber: '•••• 1099',
      status: 'suspended',
      assignmentModel: 'driver',
      assignedVehicleId: null,
      assignedRegistration: null,
      assignedDriverName: 'Sarah Khan',
      dailyLimit: 150,
      lastTransactionAt: hoursAgo(3),
    },
    {
      id: 'card-4',
      provider: 'Allstar',
      maskedNumber: '•••• 3300',
      status: 'unassigned',
      assignmentModel: 'depot',
      assignedVehicleId: null,
      assignedRegistration: null,
      assignedDriverName: null,
      dailyLimit: 300,
      lastTransactionAt: null,
    },
  ]

  const purchaseRequests: PurchaseRequestRow[] = [
    {
      id: 'pr-1',
      resourceName: 'Screenwash',
      quantity: 40,
      unit: 'L',
      estimatedCost: 48,
      vehicleId: null,
      registrationNumber: null,
      depotName: 'Wembley Depot',
      reason: 'Depot tank empty — winter wash needed before Monday runs',
      urgency: 'urgent',
      status: 'pending',
      requestedBy: 'Alice Brown',
      neededBy: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      createdAt: hoursAgo(8),
    },
    {
      id: 'pr-2',
      resourceName: 'Brake fluid DOT 4',
      quantity: 12,
      unit: 'L',
      estimatedCost: 96,
      vehicleId: 'veh-4',
      registrationNumber: 'CD34 EFG',
      depotName: 'Wembley Depot',
      reason: 'Below minimum — WO-4 may need top-up',
      urgency: 'routine',
      status: 'pending',
      requestedBy: 'Dave Wilson',
      neededBy: null,
      createdAt: daysAgo(1),
    },
  ]

  const tyres: TyreAsset[] = [
    {
      id: 'tyre-1',
      internalId: 'TY-WEM-0141',
      brand: 'Michelin',
      size: '215/75R16C',
      dotCode: '2419',
      status: 'fitted',
      treadDepthMm: 6.2,
      pressurePsi: 58,
      vehicleId: 'veh-1',
      registrationNumber: 'AB12 CDE',
      position: 'NSF',
      positionLabel: 'Nearside front',
      depotId: null,
      depotName: null,
      fittedAt: daysAgo(40),
      removedAt: null,
      retorqueDueAt: null,
      recommendation: null,
      linkedDefectId: null,
      linkedInspectionId: null,
      unitCost: 145,
    },
    {
      id: 'tyre-2',
      internalId: 'TY-WEM-0142',
      brand: 'Michelin',
      size: '215/75R16C',
      dotCode: '2419',
      status: 'fitted',
      treadDepthMm: 5.8,
      pressurePsi: 57,
      vehicleId: 'veh-1',
      registrationNumber: 'AB12 CDE',
      position: 'OSF',
      positionLabel: 'Offside front',
      depotId: null,
      depotName: null,
      fittedAt: daysAgo(40),
      removedAt: null,
      retorqueDueAt: null,
      recommendation: null,
      linkedDefectId: null,
      linkedInspectionId: null,
      unitCost: 145,
    },
    {
      id: 'tyre-3',
      internalId: 'TY-WEM-0401',
      brand: 'Goodyear',
      size: '215/75R16C',
      dotCode: '1820',
      status: 'fitted',
      treadDepthMm: 1.6,
      pressurePsi: 52,
      vehicleId: 'veh-4',
      registrationNumber: 'CD34 EFG',
      position: 'OSF',
      positionLabel: 'Offside front',
      depotId: null,
      depotName: null,
      fittedAt: daysAgo(90),
      removedAt: null,
      retorqueDueAt: null,
      recommendation: 'Replace — tread below legal margin',
      linkedDefectId: 'vdef-6',
      linkedInspectionId: 'insp-pmi-overdue',
      unitCost: 138,
    },
    {
      id: 'tyre-4',
      internalId: 'TY-WEM-0402',
      brand: 'Goodyear',
      size: '215/75R16C',
      dotCode: '2218',
      status: 'awaiting_retorque',
      treadDepthMm: 7.1,
      pressurePsi: 58,
      vehicleId: 'veh-4',
      registrationNumber: 'CD34 EFG',
      position: 'NSF',
      positionLabel: 'Nearside front',
      depotId: null,
      depotName: null,
      fittedAt: hoursAgo(10),
      removedAt: null,
      retorqueDueAt: hoursAgo(2),
      recommendation: 'Complete re-torque sign-off',
      linkedDefectId: null,
      linkedInspectionId: null,
      unitCost: 138,
    },
    {
      id: 'tyre-5',
      internalId: 'TY-WEM-STOCK-09',
      brand: 'Continental',
      size: '215/75R16C',
      dotCode: '0125',
      status: 'in_stock',
      treadDepthMm: 8.5,
      pressurePsi: null,
      vehicleId: null,
      registrationNumber: null,
      position: null,
      positionLabel: null,
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      fittedAt: null,
      removedAt: null,
      retorqueDueAt: null,
      recommendation: null,
      linkedDefectId: null,
      linkedInspectionId: null,
      unitCost: 152,
    },
    {
      id: 'tyre-6',
      internalId: 'TY-WEM-REMOVED-03',
      brand: 'Goodyear',
      size: '215/75R16C',
      dotCode: '1017',
      status: 'quarantine',
      treadDepthMm: 1.4,
      pressurePsi: null,
      vehicleId: null,
      registrationNumber: null,
      position: null,
      positionLabel: null,
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      fittedAt: null,
      removedAt: daysAgo(1),
      retorqueDueAt: null,
      recommendation: 'Dispose — uneven wear suggests alignment check',
      linkedDefectId: 'vdef-6',
      linkedInspectionId: null,
      unitCost: 0,
    },
  ]

  const equipment: EquipmentAsset[] = [
    {
      id: 'eq-1',
      qrCode: 'EQ-WEM-FA-014',
      name: 'First aid kit',
      category: 'safety_equipment',
      status: 'assigned',
      vehicleId: 'veh-1',
      registrationNumber: 'AB12 CDE',
      depotId: null,
      depotName: null,
      expiryDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      lastCheckedAt: daysAgo(3),
      requiredForDuty: true,
    },
    {
      id: 'eq-2',
      qrCode: 'EQ-WEM-EX-014',
      name: 'Fire extinguisher',
      category: 'safety_equipment',
      status: 'assigned',
      vehicleId: 'veh-1',
      registrationNumber: 'AB12 CDE',
      depotId: null,
      depotName: null,
      expiryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      lastCheckedAt: daysAgo(3),
      requiredForDuty: true,
    },
    {
      id: 'eq-3',
      qrCode: 'EQ-WEM-WC-040',
      name: 'Wheelchair restraint set',
      category: 'accessibility_equipment',
      status: 'missing',
      vehicleId: 'veh-4',
      registrationNumber: 'CD34 EFG',
      depotId: null,
      depotName: null,
      expiryDate: null,
      lastCheckedAt: daysAgo(1),
      requiredForDuty: true,
    },
    {
      id: 'eq-4',
      qrCode: 'EQ-WEM-FA-STOCK-02',
      name: 'First aid kit',
      category: 'safety_equipment',
      status: 'available',
      vehicleId: null,
      registrationNumber: null,
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      expiryDate: new Date(Date.now() + 400 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      lastCheckedAt: daysAgo(10),
      requiredForDuty: true,
    },
    {
      id: 'eq-5',
      qrCode: 'EQ-WEM-EX-EXP',
      name: 'Fire extinguisher',
      category: 'safety_equipment',
      status: 'expired',
      vehicleId: 'veh-2',
      registrationNumber: 'GH56 HIJ',
      depotId: null,
      depotName: null,
      expiryDate: daysAgo(12).slice(0, 10),
      lastCheckedAt: daysAgo(12),
      requiredForDuty: true,
    },
  ]

  const stockTransfers: StockTransferRow[] = [
    {
      id: 'xfer-1',
      resourceItemId: 'res-adblue',
      resourceName: 'AdBlue',
      quantity: 40,
      unit: 'L',
      fromDepotId: 'depot-heathrow',
      fromDepotName: 'Heathrow Depot',
      toDepotId: 'depot-wembley',
      toDepotName: 'Wembley Depot',
      status: 'in_transit',
      requestedBy: 'Alice Brown',
      createdAt: hoursAgo(5),
    },
    {
      id: 'xfer-2',
      resourceItemId: 'res-tyre-215',
      resourceName: 'Tyre 215/75R16C',
      quantity: 2,
      unit: 'each',
      fromDepotId: 'depot-wembley',
      fromDepotName: 'Wembley Depot',
      toDepotId: 'depot-heathrow',
      toDepotName: 'Heathrow Depot',
      status: 'pending',
      requestedBy: 'Tom Harris',
      createdAt: daysAgo(1),
    },
  ]

  const integrations: ResourceIntegration[] = [
    {
      id: 'int-allstar',
      provider: 'Allstar',
      category: 'fuel_card',
      status: 'configured',
      lastSyncAt: hoursAgo(12),
      notes: 'Card feed stub — reconcile against ledger nightly.',
    },
    {
      id: 'int-telematics',
      provider: 'Geotab',
      category: 'telematics',
      status: 'available',
      lastSyncAt: null,
      notes: 'Connect to pull odometer and fuel level for anomaly checks.',
    },
    {
      id: 'int-xero',
      provider: 'Xero',
      category: 'accounting',
      status: 'available',
      lastSyncAt: null,
      notes: 'Export approved fuel/VAT lines as purchase bills.',
    },
    {
      id: 'int-supplier',
      provider: 'Fleet Fluids Ltd',
      category: 'supplier',
      status: 'configured',
      lastSyncAt: daysAgo(5),
      notes: 'Invoice PDF metadata linked to purchase transactions.',
    },
    {
      id: 'int-ev',
      provider: 'Zapmap Fleet',
      category: 'ev_charging',
      status: 'available',
      lastSyncAt: null,
      notes: 'Ready when EV vehicles join the fleet.',
    },
    {
      id: 'int-dispenser',
      provider: 'Wembley yard dispenser',
      category: 'depot_dispenser',
      status: 'connected',
      lastSyncAt: hoursAgo(1),
      notes: 'AdBlue dispense events write to the resource ledger.',
    },
  ]

  const budgets: BudgetLine[] = [
    {
      id: 'bud-1',
      costCentre: 'Ops — Wembley',
      category: 'Fuel',
      period: '2026-07',
      budgetAmount: 12000,
      spentAmount: 8420,
      forecastAmount: 11850,
      status: 'on_track',
    },
    {
      id: 'bud-2',
      costCentre: 'Ops — Wembley',
      category: 'Fluids & AdBlue',
      period: '2026-07',
      budgetAmount: 1800,
      spentAmount: 1420,
      forecastAmount: 1950,
      status: 'watch',
    },
    {
      id: 'bud-3',
      costCentre: 'Fleet — Tyres',
      period: '2026-07',
      category: 'Tyres',
      budgetAmount: 3500,
      spentAmount: 3680,
      forecastAmount: 4100,
      status: 'over',
    },
    {
      id: 'bud-4',
      costCentre: 'Workshop',
      category: 'Parts & consumables',
      period: '2026-07',
      budgetAmount: 5000,
      spentAmount: 2100,
      forecastAmount: 3900,
      status: 'on_track',
    },
  ]

  const wholeLife: WholeLifeCostRow[] = [
    {
      vehicleId: 'veh-4',
      registrationNumber: 'CD34 EFG',
      resourceSpendYtd: 4120,
      estimatedRemainingLifeYears: 1.5,
      replacementSuggested: true,
      reason: 'High tyre + fluid spend with rising defect rate — review replacement window.',
    },
    {
      vehicleId: 'veh-1',
      registrationNumber: 'AB12 CDE',
      resourceSpendYtd: 1860,
      estimatedRemainingLifeYears: 4,
      replacementSuggested: false,
      reason: null,
    },
    {
      vehicleId: 'veh-2',
      registrationNumber: 'GH56 HIJ',
      resourceSpendYtd: 2540,
      estimatedRemainingLifeYears: 3,
      replacementSuggested: false,
      reason: null,
    },
  ]

  // Tyre fit ledger rows
  transactions.push(
    {
      id: 'rtx-tyre-fit-1',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceCategory: 'tyre',
      resourceItemId: 'res-tyre-215',
      resourceName: 'Tyre 215/75R16C',
      transactionType: 'fit',
      quantity: 1,
      unit: 'each',
      unitPrice: 138,
      vatAmount: 27.6,
      grossAmount: 138,
      vehicleId: 'veh-4',
      registrationNumber: 'CD34 EFG',
      driverId: null,
      driverName: null,
      staffName: 'Dave Wilson',
      supplierName: null,
      workOrderId: 'wo-4',
      defectId: 'vdef-6',
      odometer: 112400,
      fuelLevelBefore: null,
      fuelLevelAfter: null,
      fullTank: null,
      receiptFileName: null,
      fuelCardId: null,
      status: 'approved',
      anomalyFlags: [],
      notes: 'Fitted NSF — re-torque due',
      createdAt: hoursAgo(10),
      createdBy: 'Dave Wilson',
      approvedBy: 'Tom Harris',
    },
    {
      id: 'rtx-tyre-remove-1',
      depotId: 'depot-wembley',
      depotName: 'Wembley Depot',
      resourceCategory: 'tyre',
      resourceItemId: 'res-tyre-215',
      resourceName: 'Tyre 215/75R16C',
      transactionType: 'remove',
      quantity: 1,
      unit: 'each',
      unitPrice: null,
      vatAmount: null,
      grossAmount: null,
      vehicleId: 'veh-4',
      registrationNumber: 'CD34 EFG',
      driverId: null,
      driverName: null,
      staffName: 'Dave Wilson',
      supplierName: null,
      workOrderId: 'wo-4',
      defectId: 'vdef-6',
      odometer: 112400,
      fuelLevelBefore: null,
      fuelLevelAfter: null,
      fullTank: null,
      receiptFileName: null,
      fuelCardId: null,
      status: 'approved',
      anomalyFlags: [],
      notes: 'Removed worn OSF to quarantine',
      createdAt: daysAgo(1),
      createdBy: 'Dave Wilson',
      approvedBy: 'Tom Harris',
    },
  )

  stock.push({
    id: 'stk-tyre',
    depotId: 'depot-wembley',
    depotName: 'Wembley Depot',
    resourceItemId: 'res-tyre-215',
    resourceName: 'Tyre 215/75R16C',
    category: 'tyre',
    available: 3,
    reserved: 1,
    minimum: 4,
    unit: 'each',
    status: 'reorder',
  })

  return {
    catalogue: RESOURCE_CATALOGUE,
    transactions,
    stock,
    cards,
    purchaseRequests,
    tyres,
    equipment,
    stockTransfers,
    integrations,
    budgets,
    wholeLife,
    settings: { ...DEFAULT_FLEET_RESOURCES_SETTINGS },
  }
}
